<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matías Frugone-Álvarez">
<meta name="author" content="Sergio Contreras">
<meta name="author" content="Oliver Meseguer-Ruiz">
<meta name="author" content="Eduardo Tejos">
<meta name="author" content="Antonio Delgado-Huertas">
<meta name="author" content="Blas Valero-Garcés">
<meta name="author" content="Francisca Diaz">
<meta name="author" content="Matías Briseño,">
<meta name="author" content="Manuel Bustos-Morales,">
<meta name="author" content="Claudio Latorre,">
<meta name="keywords" content="Leaf cuticular waxes, Rodent Middens, Atacama Desert, Hydroclimate, Quaternary">

<title>Hydroclimate variations over the last 17,000 years as measured by leaf waxes in vegetation physiognomic and rodent middens from the south-central Atacama Desert, Chile</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="Matías Frugone-Álvarez_files/libs/clipboard/clipboard.min.js"></script>
<script src="Matías Frugone-Álvarez_files/libs/quarto-html/quarto.js"></script>
<script src="Matías Frugone-Álvarez_files/libs/quarto-html/popper.min.js"></script>
<script src="Matías Frugone-Álvarez_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Matías Frugone-Álvarez_files/libs/quarto-html/anchor.min.js"></script>
<link href="Matías Frugone-Álvarez_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Matías Frugone-Álvarez_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Matías Frugone-Álvarez_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Matías Frugone-Álvarez_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Matías Frugone-Álvarez_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
</head><body class="fullcontent">\usepackage{setspace}
\doublespacing
\usepackage{lineno}
\linenumbers

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>





<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hydroclimate variations over the last 17,000 years as measured by leaf waxes in vegetation physiognomic and rodent middens from the south-central Atacama Desert, Chile</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    Matías Frugone-Álvarez 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Católica de la Santísima Concepción
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Sergio Contreras 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Católica de la Santísima Concepción
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Oliver Meseguer-Ruiz 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad de Tarapacá
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Eduardo Tejos 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad Católica de la Santísima Concepción
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Antonio Delgado-Huertas 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidad de Granada
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Blas Valero-Garcés 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Instituto Pirenaico de Ecología-CSIC
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Francisca Diaz 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Pontificia Universidad Católica de Chile
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Matías Briseño, 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Pontificia Universidad Católica de Chile
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Manuel Bustos-Morales, 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Pontificia Universidad Católica de Chile
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    Claudio Latorre, 
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Pontificia Universidad Católica de Chile
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstract</div>
    <p>Leaf cuticular waxes are one of the main environment-plant interaction structure systems that enable desert plants to resist extreme climates. We present a long chain n-alkyl lipids study from fresh plant leaves collected along an elevational gradient and from 28 rodent paleomiddens collected from Quebrada Incahuasi (25.6 ºS, 3,600 m asl) in the south-central Atacama Desert of Chile spanning the last 17 ka cal BP. The dominant Atacama plant associations (from the coastal Atacama to the Andean Steppe) are characterized by long-chain (&gt;C24) n-alkanes and n-alkanoic acids. Their specific distribution (i.e.&nbsp;Average Chain Length [ACL] and Carbon Preference Index [CPI]) can be associated with the climatic conditions along our studied gradient. The sum of leaf wax n-alkanes shows the highest concentrations associated with wet conditions, whereas n-alkanoic acids (between n-C24 and n-C28) increase with hiperaridity. In fact, paleomidden n-alkane time series showed a similar change where the greatest changes in leaf wax n-alkane distribution (ACL and CPI) coincided with the greatest increase in moisture during the Central Andean Pluvial Event (CAPE; between 18 and 9 ka cal BP) and the Late Holocene. The shift in paleomidden n-alkanes distribution is corroborated by the relative abundance of rainfall-dependent extra-local taxa. This is the first study reporting leaf wax content obtained from ancient rodent middens, and shows promising results as a robust hydroclimate proxy for this arid region.</p>
  </div>
</div>

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Establishing the magnitude and timing of past climate changes that have modulated landscape dynamics forms part of the necessary knowledge for achieving sustainable social-ecological systems on a warming planet <span class="citation" data-cites="berdugoGlobalEcosystemThresholds2020 lavorelPredictingChangesCommunity2002 mucinaBiomeEvolutionCrucial2019">(<a href="#ref-berdugoGlobalEcosystemThresholds2020" role="doc-biblioref">Berdugo et al. 2020</a>; <a href="#ref-lavorelPredictingChangesCommunity2002" role="doc-biblioref">Lavorel and Garnier 2002</a>; <a href="#ref-mucinaBiomeEvolutionCrucial2019" role="doc-biblioref">Mucina 2019</a>)</span>. However, we do not know ecosystem’s nonlinear responses and thresholds to extreme and abrupt climatic variations, nor how these affect ecological adaptation and the configuration of landscape physiognomy <span class="citation" data-cites="berdugoGlobalEcosystemThresholds2020 eshelPlantEcologicalGenomics2021 halbritterTraitDifferentiationAdaptation2018">(<a href="#ref-berdugoGlobalEcosystemThresholds2020" role="doc-biblioref">Berdugo et al. 2020</a>; <a href="#ref-eshelPlantEcologicalGenomics2021" role="doc-biblioref">Eshel et al. 2021</a>; <a href="#ref-halbritterTraitDifferentiationAdaptation2018" role="doc-biblioref">Halbritter et al. 2018</a>)</span>.</p>
<p>The central Andes, a natural laboratory for understanding biological responses to extreme environmental changes, has experienced pronounced hydroclimatic variations throughout the Quaternary that are unprecedented in the instrumental record <span class="citation" data-cites="arroyoPlantPhenologicalPatterns1981 betancourt22000YearRecord2000 gayoLateQuaternaryHydrological2012 grosjeanMidHoloceneClimateSouthCentral2001 houstonCentralAndeanWestslope2003 jaraDidModernPrecipitation2022 latorreVegetationInvasionsAbsolute2002 quadeCentralAndean282022 rechLateQuaternaryPaleohydrology2002 rodbell700000Years2022 strikisSouthAmericanMonsoon2018">(<a href="#ref-arroyoPlantPhenologicalPatterns1981" role="doc-biblioref">Arroyo, Armesto, and Villagran 1981</a>; <a href="#ref-betancourt22000YearRecord2000" role="doc-biblioref">J. L. Betancourt et al. 2000</a>; <a href="#ref-gayoLateQuaternaryHydrological2012" role="doc-biblioref">Gayo et al. 2012</a>; <a href="#ref-grosjeanMidHoloceneClimateSouthCentral2001" role="doc-biblioref">Grosjean 2001</a>; <a href="#ref-houstonCentralAndeanWestslope2003" role="doc-biblioref">Houston and Hartley 2003</a>; <a href="#ref-jaraDidModernPrecipitation2022" role="doc-biblioref">Jara, Maldonado, and de Porras 2022</a>; <a href="#ref-latorreVegetationInvasionsAbsolute2002" role="doc-biblioref">Latorre et al. 2002</a>; <a href="#ref-quadeCentralAndean282022" role="doc-biblioref">Quade et al. 2022</a>; <a href="#ref-rechLateQuaternaryPaleohydrology2002" role="doc-biblioref">Rech, Quade, and Betancourt 2002</a>; <a href="#ref-rodbell700000Years2022" role="doc-biblioref">Rodbell et al. 2022</a>; <a href="#ref-strikisSouthAmericanMonsoon2018" role="doc-biblioref">Stríkis et al. 2018</a>)</span>. Numerous geological records from the western Central Andes have documented the impacts of at least four global/regional climatic changes during the last glacial termination. The Central Andean Pluvial Event (CAPE) <span class="citation" data-cites="latorreLateQuaternaryVegetation2006 martinLakeTaucaHighstand2018 nesterPerennialStreamDischarge2007 quadeCentralAndean282022 quadePaleowetlandsRegionalClimate2008">(<a href="#ref-latorreLateQuaternaryVegetation2006" role="doc-biblioref">Latorre, Betancourt, and Arroyo 2006</a>; <a href="#ref-martinLakeTaucaHighstand2018" role="doc-biblioref">Martin et al. 2018</a>; <a href="#ref-nesterPerennialStreamDischarge2007" role="doc-biblioref">Nester et al. 2007</a>; <a href="#ref-quadeCentralAndean282022" role="doc-biblioref">Quade et al. 2022</a>, <a href="#ref-quadePaleowetlandsRegionalClimate2008" role="doc-biblioref">2008</a>)</span>; subdivided into CAPE I <span class="citation" data-cites="gayoLateQuaternaryHydrological2012">(from ca. 18 and 14 ka cal BP, <a href="#ref-gayoLateQuaternaryHydrological2012" role="doc-biblioref">Gayo et al. 2012</a>)</span> and CAPE II <span class="citation" data-cites="quadePaleowetlandsRegionalClimate2008">(ca. 13 to 9 ka cal BP, <a href="#ref-quadePaleowetlandsRegionalClimate2008" role="doc-biblioref">Quade et al. 2008</a>)</span> was interrupted by a millennial-scale drought between c.&nbsp;14-13 ka cal BP <span class="citation" data-cites="workmanLandscapeEvolutionEnvironmental2020">(<a href="#ref-workmanLandscapeEvolutionEnvironmental2020" role="doc-biblioref">Workman et al. 2020</a>)</span>. A period of extreme aridity prevailed at the onset of the Middle Holocene <span class="citation" data-cites="gonzalez-pinillaHighLowlatitudeForcings2021 grosjeanLateglacialEarlyMiddle1994 valero-garcesLimnogeologyLagunaMiscanti1996">(ca. 8-7 and 5-4 ka cal BP, <a href="#ref-gonzalez-pinillaHighLowlatitudeForcings2021" role="doc-biblioref">González-Pinilla et al. 2021</a>; <a href="#ref-grosjeanLateglacialEarlyMiddle1994" role="doc-biblioref">Grosjean and Núñez 1994</a>; <a href="#ref-valero-garcesLimnogeologyLagunaMiscanti1996" role="doc-biblioref">Valero-Garcés et al. 1996</a>)</span>. A wet Medieval Climate Anomaly (MCA) between ca. 950 and 750 a cal BP <span class="citation" data-cites="luningMedievalClimateAnomaly2019 vonguntenQuantitativeHighresolutionSummer2009">(<a href="#ref-luningMedievalClimateAnomaly2019" role="doc-biblioref">Lüning et al. 2019</a>; <a href="#ref-vonguntenQuantitativeHighresolutionSummer2009" role="doc-biblioref">von Gunten et al. 2009</a>)</span>, relatively well described only in a few records was followed by drought at the onset of the Little Ice Age (LIA) ca. 650 and 100 a cal BP <span class="citation" data-cites="gonzalez-pinillaHighLowlatitudeForcings2021 mujicaLateQuaternaryClimate2015 rabatelChronologyLittleIce2008b rabatelDatingLittleIce2005">(<a href="#ref-gonzalez-pinillaHighLowlatitudeForcings2021" role="doc-biblioref">González-Pinilla et al. 2021</a>; <a href="#ref-mujicaLateQuaternaryClimate2015" role="doc-biblioref">Mujica et al. 2015</a>; <a href="#ref-rabatelChronologyLittleIce2008b" role="doc-biblioref">Rabatel et al. 2008</a>, <a href="#ref-rabatelDatingLittleIce2005" role="doc-biblioref">2005</a>)</span>. It is not entirely clear what impact these changes had on vegetation physiognomy and how it reconfigured in response to climatic dynamics or whether, on the contrary, species distributions remained relatively similar to their current floristic diversity <span class="citation" data-cites="diazRodentMiddensReveal2012">(<a href="#ref-diazRodentMiddensReveal2012" role="doc-biblioref">Díaz et al. 2012</a>)</span>. The studies of sedimentary pollen sequences, plant macrofossil remains from palaeomiddens and climatic niche models show that Atacama ecosystems can be highly resilient to past climatic changes <span class="citation" data-cites="anjosMeasuringResilienceAssessing2018 diazMultiscaleClimateChange2019 latorreVegetationInvasionsAbsolute2002 maldonadoPollenAnalyses502005">(<a href="#ref-anjosMeasuringResilienceAssessing2018" role="doc-biblioref">Anjos and Toledo 2018</a>; <a href="#ref-diazMultiscaleClimateChange2019" role="doc-biblioref">Díaz et al. 2019</a>; <a href="#ref-latorreVegetationInvasionsAbsolute2002" role="doc-biblioref">Latorre et al. 2002</a>; <a href="#ref-maldonadoPollenAnalyses502005" role="doc-biblioref">Maldonado et al. 2005</a>)</span>. Recurrently, palaeomiddens contain remains of extra-local taxa (species outside their current distribution range) that coincide with stage or pulses of increased or decreased moisture, suggesting plant incursions into completely different environments today <span class="citation" data-cites="latorreVegetationInvasionsAbsolute2002">(<a href="#ref-latorreVegetationInvasionsAbsolute2002" role="doc-biblioref">Latorre et al. 2002</a>)</span>. This redistribution of species inferred from the geological record resulting from environmental changes, implies that Atacama plant communities exhibit greater plasticity than observed at present, capable of configuring plant assemblages that we do not currently find in these environments <span class="citation" data-cites="navarroPhenotypicPlasticitySelection2022 stotzGlobalTrendsPhenotypic2021">(<a href="#ref-navarroPhenotypicPlasticitySelection2022" role="doc-biblioref">Navarro et al. 2022</a>; <a href="#ref-stotzGlobalTrendsPhenotypic2021" role="doc-biblioref">Stotz et al. 2021</a>)</span>.</p>
<p>The photosynthetic part of the plant is one of the plant structures best adapted to tolerate extreme environmental conditions and the leaves of Atacama plants are highly specialized to tolerate high levels of temperature, humidity, radiation, salinity, wind and herbivory stresses <span class="citation" data-cites="dussarratPredictiveMetabolomicsMultiple2022 eshelPlantEcologicalGenomics2021">(<a href="#ref-dussarratPredictiveMetabolomicsMultiple2022" role="doc-biblioref">Dussarrat et al. 2022</a>; <a href="#ref-eshelPlantEcologicalGenomics2021" role="doc-biblioref">Eshel et al. 2021</a>)</span>. Cuticular waxes play a fundamental role in protecting plants from these stressors <span class="citation" data-cites="pollardBuildingLipidBarriers2008">(<a href="#ref-pollardBuildingLipidBarriers2008" role="doc-biblioref">Pollard et al. 2008</a>)</span>. These waxes are mostly exuded from the leaves of plants and occur in small quantities <span class="citation" data-cites="eglintonChemicalFossilsCombined1973">(<a href="#ref-eglintonChemicalFossilsCombined1973" role="doc-biblioref">Eglinton 1973</a>)</span>. Chemically, leaf waxes are aliphatic hydrocarbon structures (mixtures of n-alkanoic acids, n-alkanes, n-alkanols, aldehydes and wax esters) highly persistent over time and have long been considered geochemical biomarkers of higher plants in the palaeoenvironmental record <span class="citation" data-cites="didykOrganicGeochemicalIndicators1978 kolattukudyPlantWaxes1970">(<a href="#ref-didykOrganicGeochemicalIndicators1978" role="doc-biblioref">Didyk et al. 1978</a>; <a href="#ref-kolattukudyPlantWaxes1970" role="doc-biblioref">Kolattukudy 1970</a>)</span>. This interest is mainly due to the relationships that have been found between their molecular abundances and isotopic fingerprint with climatic and environmental changes <span class="citation" data-cites="castanedaReviewMolecularOrganic2011 chikaraishiCompoundspecificDDD13C2003 inglisBiomarkerApproachesReconstructing2022 sachseDDValuesIndividual2006 schefussCarbonIsotopeAnalyses2003 smithInfluencePhysiologyClimate2006">(<a href="#ref-castanedaReviewMolecularOrganic2011" role="doc-biblioref">Castañeda and Schouten 2011</a>; <a href="#ref-chikaraishiCompoundspecificDDD13C2003" role="doc-biblioref">Chikaraishi and Naraoka 2003</a>; <a href="#ref-inglisBiomarkerApproachesReconstructing2022" role="doc-biblioref">Inglis et al. 2022</a>; <a href="#ref-sachseDDValuesIndividual2006" role="doc-biblioref">Sachse, Radke, and Gleixner 2006</a>; <a href="#ref-schefussCarbonIsotopeAnalyses2003" role="doc-biblioref">Schefuß et al. 2003</a>; <a href="#ref-smithInfluencePhysiologyClimate2006" role="doc-biblioref">Smith and Freeman 2006</a>)</span>. In the Atacama Desert, little is known about the composition and distribution of n-alkyl compounds in plant communities and their relationship to past climatic changes <span class="citation" data-cites="contrerasLeafWaxComposition2022 morchenFingerprintPlantLife2021">(<a href="#ref-contrerasLeafWaxComposition2022" role="doc-biblioref">Contreras et al. 2022</a>; <a href="#ref-morchenFingerprintPlantLife2021" role="doc-biblioref">Mörchen et al. 2021</a>)</span>. The n-alkane abundance and distribution in different functional types of terrestrial plants show that <span class="math inline">\(C_{31}\)</span> alkane predominates in grasses and <span class="math inline">\(C_{27}\)</span> and <span class="math inline">\(C_{29}\)</span> alkanes in woody plants <span class="citation" data-cites="bushLeafWaxNalkane2013">(<a href="#ref-bushLeafWaxNalkane2013" role="doc-biblioref">Bush and McInerney 2013</a>)</span>. Recent studies on n-alkanes in Atacama plants show a predominant distribution of long chains related to moisture sources rather than a chemo-taxonomic marker of plants studied <span class="citation" data-cites="morchenFingerprintPlantLife2021">(<a href="#ref-morchenFingerprintPlantLife2021" role="doc-biblioref">Mörchen et al. 2021</a>)</span>. Similarly, <span class="citation" data-cites="contrerasLeafWaxComposition2022">(<a href="#ref-contrerasLeafWaxComposition2022" role="doc-biblioref">Contreras et al. 2022</a>)</span> found significant negative correlations between fatty acid Carbon Preference Index (CPI) and n-alkane Average Chain Length (ACL) from Tillandsia landbeckii (CAM plant), both measures of leaf wax distribution, with both precipitation and surface evaporation; a species highly specialized in capturing moisture from coastal fog, which points to adaptations to low moisture availability along the coast.</p>
<p>This research addresses whether it is possible to identify changes in aridity and detect the transgression of extra-local taxa in the landscape physiognomy by studying leaf n-alkyl lipid abundances in a series of palaeomiddens across major climatic transitions in the Atacama Desert during the last 17 ka cal BP. The study first measured the abundance and distribution in present-day leaf waxes of dominant landscape plants along an altitudinal transect from the coast to the Andes in the Atacama region. The n-alkanes from this vegetation were then used to compare the distributions and abundances of long chain n-alkanes obtained from a series of fossil middens for: 1) the n-alkanes are the most studied waxes in the palaeoenvironmental record, 2) they are found in high concentrations in the palaeomiddens, and 3) there are current studies of waxes from other places in the Atacama Desert with which to compare our results. In the following sections, we will describe the abundances and distributions of leaf waxes along an altitudinal gradient in the Atacama Desert, and then illustrate for the first time them application as a hydroclimate proxy in a series of palaeomiddens located in the south-central Atacama Desert, along a transition zone between a high elevation vegetation belt and absolute desert. Finally, we interpret and discuss the implications of changes in the abundance and distribution of leaf wax n-alkanes in the context of changes in the plant physiognomy of the Atacama environments and their contribution as a proxy for palaeoenvironmental reconstructions in arid zones.</p>
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/Fig_1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Local and regional context of vegetational and paleomiddens site in the southern Central Andes in the Atacama Desert, Chile. (a) Random forests (RF) correlations between total abundance (µg/g) of n-alkyl lipids (n-alkanoic acids and n-alkanes of plants and lacustrine surface-sediments of Miscanti and Miñique lakes) and climatic features (precipitation and temperature) along an elevation gradient of the Atacama Desert. (b) Mean Annual Precipitation and sources of air masses that contribute moisture to the Atacama Desert and Western Cordillera of the Andes (TrM: Tropical maritime source; TeM: temperate maritime source; Tc:temperate continental source and Tr: tropical continental source. Modified from Houston and Latorre, 2022) and (c) Annual Mean Temperature.</figcaption><p></p>
</figure>
</div>
</section>
<section id="material-and-methods" class="level1">
<h1>Material and methods</h1>
<section id="site-description-and-sampling" class="level2">
<h2 class="anchored" data-anchor-id="site-description-and-sampling">Site description and sampling</h2>
<p>The Atacama Desert extends over more than 128,000 km2 between the Pacific Ocean and the plateau of the western slopes of the Andes Mountains. The aridity and hyperaridity of the Atacama Desert are due to a combination of three main factors; rain shadow created by high Andes and Altiplano, the temperature inversions along the Pacific coast at ca. 1000 m asl and the blocking of moisture from westerlies by the South Pacific High. The plant richness pattern from the Atacama Desert is strongly related to environmental factors generating vegetation “belts” or zones <span class="citation" data-cites="diazMultiscaleClimateChange2019 diazNitrogenCyclingExtreme2016 villagranVegetationHighAndean1981">(<a href="#ref-diazMultiscaleClimateChange2019" role="doc-biblioref">Díaz et al. 2019</a>, <a href="#ref-diazNitrogenCyclingExtreme2016" role="doc-biblioref">2016</a>; <a href="#ref-villagranVegetationHighAndean1981" role="doc-biblioref">C. Villagrán, Armesto, and Kalin Arroyo 1981, Figure&nbsp;1</a>)</span>. We used the plant physiognomy <span class="citation" data-cites="villagranEfectosDesertizacionDistribucion1983 arroyoPlantPhenologicalPatterns1981">(<a href="#ref-villagranEfectosDesertizacionDistribucion1983" role="doc-biblioref">Carolina Villagrán, Kalin Arroyo, and Marticorena 1983</a>; <a href="#ref-arroyoPlantPhenologicalPatterns1981" role="doc-biblioref">Arroyo, Armesto, and Villagran 1981</a>)</span> to define six vegetation belts or zones (Steppe; 4,500-4,000 m asl, Puna; 4,000-3,300 m asl, Prepuna; 3,300-2,400 m asl, Absolute Desert; 2,400-2,000 m asl, Desert; 1,000-2,000 m asl and Coastal Desert; 1,000-0 m asl) to categorize and characterize the leaf wax n-alkanoic acid and n-alkane abundance (<a href="#fig-1">Figure&nbsp;1</a> and Table 1). Modern plant sampling was carried out in August 2018 during the dry season in the Atacama Desert. We collected fresh leaves of the dominant species in 15 sites along an elevation gradient from the coast (MAP; ~ 4 mm, MAT; ~ 14<span class="math inline">\(^\circ\)</span>C) until 4,300 m asl following the methodology described in <span class="citation" data-cites="diazMultiscaleClimateChange2019 diazNitrogenCyclingExtreme2016">(<a href="#ref-diazMultiscaleClimateChange2019" role="doc-biblioref">Díaz et al. 2019</a>; <a href="#ref-diazNitrogenCyclingExtreme2016" role="doc-biblioref">Díaz et al. 2016</a>,as shown in <a href="#fig-1" role="doc-biblioref">Figure&nbsp;1</a>)</span>. We selected the dominant species (at least 50<span class="math inline">\(\%\)</span> plant cover at each site) from each vegetation belt for wax analysis. The plants were collected, pressed and dried in the field, and later placed in a drying oven at 50<span class="math inline">\(^\circ\)</span>C in the laboratory (see Supplementary Table 2). We selected thirteen species for molecular analyses based on their abundance distribution within each zone (<em>Aloysia deserticola</em>, <em>Atriplex imbricata</em>, <em>Atriplex</em> sp., <em>Cristaria foliosa</em>, <em>Ephedra</em> sp., <em>Haplopappus rigidus</em>, <em>Pappostipa frigida</em> (<em>Stippa frigida</em>), <em>Pappostipa</em> sp., <em>Junellia seriphioides</em>, <em>Nolana aplocaryoides</em>, <em>Perityle emoryi</em>, <em>Tiquilia atacamensis</em>). In 2017, we collected 28 rodent middens from Quebrada Incahuasi (QIN; 25<span class="math inline">\(^\circ\)</span>C 35’ 52”S, 69<span class="math inline">\(^\circ\)</span>C 14’ 18” W) located west hillside of the Domeyko mountain between 3,530 and 3,620 m asl (Table 2). In this area, Puna vegetation appears between 3,200 and 4,000 m asl and consists mostly of widely spaced shrubland plants; it is characterized by the shrubs <em>Junellia bryoides</em>, <em>Ephedra americana</em>, <em>Maihueniopsis</em> sp., <em>Cryptantha</em> sp., <em>Pappostipa frigida</em>, <em>Baccharis tola</em>, <em>Haplopappus</em> sp., <em>Gillia</em> sp., <em>Cistante</em> sp., <em>Adesmia hysterix</em>, <em>Phacelia cumingii</em> and <em>Phacelia pinnatifida</em>.</p>
</section>
<section id="rodent-middens-and-macrofossil-analysis" class="level2">
<h2 class="anchored" data-anchor-id="rodent-middens-and-macrofossil-analysis">Rodent middens and macrofossil analysis</h2>
<p>Fossil rodent middens were collected in October 2003 from Quebrada Incahuasi along ignimbrite overhangs and rock shelters. Quebrada Incahuasi (QIN) is an east-trending, short, narrow valley located above 3500 m asl. The valley heads into the Altiplano (Atacama Region) at over 4300 m asl. Large alluvial fans stem from the northern and southern ignimbrite cliffs and escarpments to the bottom of the valley. Middens were collected mostly along these escarpments. Vegetation in the valley is mostly contracted (i.e., mostly occurs in places along cliff walls or in the dry washes and other places where water accumulates) and is dominated by shrubs (<em>Junellia bryoides</em>, <em>Baccharis tola</em>, <em>Haplopappus rigidus</em>) and steppe grasses (<em>Pappostipa frigida</em>). Middens were processed following previously described procedures (<span class="citation" data-cites="betancourt22000YearRecord2000 betancourtPaleomadriguerasRoedoresNuevo2002 latorreVegetationInvasionsAbsolute2002">(<a href="#ref-betancourt22000YearRecord2000" role="doc-biblioref">J. L. Betancourt et al. 2000</a>; <a href="#ref-betancourtPaleomadriguerasRoedoresNuevo2002" role="doc-biblioref">Julio L. Betancourt and Saavedra 2002</a>; <a href="#ref-latorreVegetationInvasionsAbsolute2002" role="doc-biblioref">Latorre et al. 2002</a>)</span>). A modern analogue approach was used to control for the presence of extra-local species in the record; we collected all plant species present to within 500 m around each midden and compared it with the regional vegetation. Midden fecal-pellet sizes and shapes are used for distinguishing the midden-forming agents. Plant macrofossils were quantified and identified by comparison with the plants collected at the sites and a reference collection at the Laboratory of Paleoecology and Paleoenvironments of the Department of Ecology, P. Universidad Católica de Chile. Based on the foregoing analysis, annual, herbaceous, perennial plants, as well as, Puna, Prepuna and Steppe affinities were identified. Taxa present in each midden were quantified with a relative abundance index <span class="citation" data-cites="spaulding1990vegetational">(where 0 is absent and 5 is dominant, <a href="#ref-spaulding1990vegetational" role="doc-biblioref">Spaulding 1990</a>)</span>. Approximately 100 mg of rodent feces from each of the 31 middens were submitted for 14C dating at the Accelerator mass spectrometry (AMS) laboratory at University of California Irvine (UC Irvine). Radiocarbon ages were calibrated using the SHCal20 calibration curve <span class="citation" data-cites="hogg_2020">(<a href="#ref-hogg_2020" role="doc-biblioref">Hogg et al. 2020</a>)</span> and reported in ka (thousands of calibrated years before present – defined as ad 1950).</p>
</section>
<section id="extraction-and-quantification-of-n-alkanes-and-n-alkanoic-acids" class="level2">
<h2 class="anchored" data-anchor-id="extraction-and-quantification-of-n-alkanes-and-n-alkanoic-acids">Extraction and quantification of n-alkanes and n-alkanoic acids</h2>
<p>The total lipid extract (TLE) was obtained using a Milestone Ethos Easy Microwave Assisted Extraction (MAE) system by extracting 0.5 g of dry leaf with 20 ml dichloromethane:methanol (DCM:MeOH) (9:1, v/v). 25 µL of an internal standard mixture of known concentration (containing 1000 ng/µL of cis-10-nonadecenoic acid, 5 alpha-cholestane and nonadecanol) was added. The MAE was programmed with a ramp to 100 ºC at 10 ºC min -1, a hold time at 100 ºC for 15 min, and a cooling time of 30 min. A blank was included in each sample set, to test the presence of contaminants prior to sample analysis. The TLE was separated into three fractions using aminopropyl solid phase separation columns, eluting first with DCM:2-propanol (2:1, v/v) (n-alkane; neutral fraction), glacial acetic acid (GAA):ether (1:24, v/v) (n-alkanoic acid; fatty acid fraction) and MeOH at 100% (phospholipid fraction). The neutral fraction was eluted through activated (at 450 ºC) silica gel using hexane for n-alkanes. The n-alkanoic acids were derivatized with methanolic boron trifluoride (BF3:MeOH), forming fatty acid methyl esters (FAMEs).</p>
</section>
<section id="n-alkanoic-acids-and-n-alkanes-molecular-parameters" class="level2">
<h2 class="anchored" data-anchor-id="n-alkanoic-acids-and-n-alkanes-molecular-parameters">n-alkanoic acids and n-alkanes molecular parameters</h2>
<p>The n-alkanoic acids and n-alkanes waxes were quantified using gas chromatography with flame ionization detection (GC-FID 7890A; Agilent Technologies) and identified via GC–mass spectrometry (GC–MS:QP-5050A-Shimadzu) based on retention time and spectra of standards for each compound. Peak areas from GC-FID chromatograms were manually integrated to quantify the abundances by comparing with the area of a co-injected standard of known concentration (5⍺-Androstane). Total n-alkane and n-alkanoic acid concentrations in µg g −1 dry weight (dw) were calculated as the sum of n-C19 to n-C33 and n-C18 to n-C34 (odd as well as even ones), respectively. The n-alkanoic acids and n-alkanes leaf wax abundance was calculated per unit dry leaf mass (µg/g). The leaf wax distribution was calculated using the ACL and CPI for n-alkanoic acids and n-alkanes or all samples as shown below:</p>
<p><span class="math display">\[
ACL_{(a-b)} = \sum\limits_{i=a}^{b}\frac{i\cdot {C_{i}}}{C_{i}}
\]</span></p>
<p>where a-b and Ci indicate the range of carbon-chain length and the concentration odd and even for n-alkanes (ACL23-33) and n-alkanoic acids (ACL24-34), respectively.</p>
<p><span class="math display">\[
CPI_{(alkanes)} = 0.5 \cdot \left[(\frac{\sum C_{even}}{\sum C_{odd}}) + (\frac{\sum C_{even}}{\sum C_{odd}})\right]
\]</span></p>
<p>and</p>
<p><span class="math display">\[
CPI_{(FAME_{s})} = 0.5 \cdot \left[(\frac{\sum C_{odd}}{\sum C_{even}}) + (\frac{\sum C_{odd}}{\sum C_{even}})\right]
\]</span></p>
<p>Ceven (carbon 23 to 33) and Codd (carbon 24 to 32) indicate the carbon-chain length abundance even and odd, respectively.</p>
</section>
<section id="climate-and-waxes-analysis" class="level2">
<h2 class="anchored" data-anchor-id="climate-and-waxes-analysis">Climate and waxes analysis</h2>
<p>To study the relationship between n-alkyl lipid total abundances and climate, we use the CR2MET gridded product which contains regional precipitation, average temperature, minimum temperature and maximum temperature values with a resolution of 0.05 degrees (https://www.cr2.cl/datos-productos-grilados/). From this dataset, we calculated 19 bioclimatic layers that were used to evaluate different predictive supervised models of n-alkanes from no more than 3 input parameters. The sensitivity of the best models was evaluated through the boostrapping method. Random Forests (RF) correlations were applied using the scipy library in python3.4.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="abundance-and-distribution-of-long-chain-c21-n-alkyl-leaf-waxes-along-an-environmental-gradient-in-the-atacama-desert." class="level2">
<h2 class="anchored" data-anchor-id="abundance-and-distribution-of-long-chain-c21-n-alkyl-leaf-waxes-along-an-environmental-gradient-in-the-atacama-desert.">Abundance and distribution of long-chain (&gt;C21) n-alkyl leaf waxes along an environmental gradient in the Atacama Desert.</h2>
<p>The vegetational gradient was dominated by twelve species (~80% landscape); Pappostipa frigida, Atriplex imbricata, Haplopappus rigidus, Ephedra americana, Aloysia deserticola, Junellia seriphioides, Tiquilia atacamensis, Cristaria integerrima, Nolana aplocaryoides, Perityle emoryi and two unidentified species in the coast (see Table 1 and Figure 1S). Figure 1 shows the climatic correlations with individual abundances of each long-chain n-alkyl (n-alkane and fatty acid) leaf wax. Total leaf wax abundance showed a strong second-degree correlation (R2= 0.86 +/- 0.11) with altitudinal cline (Figure 1b). Additionally, these results showed positive correlations with annual mean, annual mean maximum, and annual mean minimum temperature, and negative correlations with annual mean precipitation (Figures S3 and S4). The long chains between n-C26 and n-C29 showed the highest correlation (between R2 = 0.4 and R2 = 0.6) values in all the variables analyzed (see Figures 2S and 3S). In general, we observe a high variability of total abundances in the chain-length of waxes within and between vegetation belts (Figures 1 and 2S). The concentration of n-alkyl foliar waxes tends to be higher in the Coastal, Prepuna and Puna zones compared to the Hyperarid and Steppe, which have the most extreme environmental conditions (Figure 1a and 2S). The highest abundances of n-alkyl waxes occur between 50-200 and 2,500 to 3,700 m asl, coincident with zones with the greatest species richness and abundance. The lower individual molecular abundances were observed in the Hyperarid core (~2,000 to 2,300 m asl) and high Andean altitude (4,000 to 4,400 m asl). The odd-over-even and even-over-odd chain-lengths distributions of n-alkanes and n-alkanoic were more abundant between n-C25 to n-C31 and n-C24 to n-C30, respectively (Figure 2a). The leaf wax n-alkanes and n-alkanoic acids abundance of surface sediment from two brackish lakes in the Atacama Altiplano (Miscanti and Miñiques lakes at 4,200 m asl) showed similar total abundance values to the Steppe but different distribution i.e.&nbsp;CPI and ACL (Figures 2b). The leaf wax n-alkanoic acids (n=3) and n-alkanes (n=6) abundances in these lake sediments were of 375.88 +/- 52 ug/g dw (CPI_median = 11 +/- 2.6; ACL_median = 24.25 +/- 0.07, Table 1) and 10.45 +/- 5 ug/g dw (CPI_median = 9 +/- 1.98; ACL_median = 25.92 +/- 0.63, Table 1), respectively. In n-alkanoic acids, carbon chain-lengths distribution of most abundant chain length is between n-C18 and n-C34 with a higher abundance of short and medium chain (n-C18 to n-C24) and dominance of the carbon length chain n-C18. The high and medium molecular weight ranges are the minority (n-C26 to n-C3) and represent ca. 20% of the n-alkanoic acids in the sediments. In n-alkane, carbon chain-lengths distribution is between n-C23 and n-C33 with a higher abundance of medium and high molecular weight n-C23 and n-C29, however, the abundances were lower than fatty acid (Figure 2).</p>
<div class="cell">
<div class="cell-output-display">

<div id="nkeovfxosf" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

:where(#nkeovfxosf) .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

:where(#nkeovfxosf) .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

:where(#nkeovfxosf) .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

:where(#nkeovfxosf) .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

:where(#nkeovfxosf) .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

:where(#nkeovfxosf) .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

:where(#nkeovfxosf) .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

:where(#nkeovfxosf) .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

:where(#nkeovfxosf) .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

:where(#nkeovfxosf) .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

:where(#nkeovfxosf) .gt_from_md > :first-child {
  margin-top: 0;
}

:where(#nkeovfxosf) .gt_from_md > :last-child {
  margin-bottom: 0;
}

:where(#nkeovfxosf) .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

:where(#nkeovfxosf) .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#nkeovfxosf) .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

:where(#nkeovfxosf) .gt_row_group_first td {
  border-top-width: 2px;
}

:where(#nkeovfxosf) .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#nkeovfxosf) .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_first_summary_row.thick {
  border-top-width: 2px;
}

:where(#nkeovfxosf) .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#nkeovfxosf) .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

:where(#nkeovfxosf) .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#nkeovfxosf) .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

:where(#nkeovfxosf) .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

:where(#nkeovfxosf) .gt_left {
  text-align: left;
}

:where(#nkeovfxosf) .gt_center {
  text-align: center;
}

:where(#nkeovfxosf) .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

:where(#nkeovfxosf) .gt_font_normal {
  font-weight: normal;
}

:where(#nkeovfxosf) .gt_font_bold {
  font-weight: bold;
}

:where(#nkeovfxosf) .gt_font_italic {
  font-style: italic;
}

:where(#nkeovfxosf) .gt_super {
  font-size: 65%;
}

:where(#nkeovfxosf) .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

:where(#nkeovfxosf) .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

:where(#nkeovfxosf) .gt_indent_1 {
  text-indent: 5px;
}

:where(#nkeovfxosf) .gt_indent_2 {
  text-indent: 10px;
}

:where(#nkeovfxosf) .gt_indent_3 {
  text-indent: 15px;
}

:where(#nkeovfxosf) .gt_indent_4 {
  text-indent: 20px;
}

:where(#nkeovfxosf) .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <caption>Table 1. Summary statistics of leaf wax n-alkanes and fatty acids abundance</caption>
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="wax">wax</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="n">n</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mean_abundance">mean_abundance</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="sd_abundance">sd_abundance</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="median_CPI">median_CPI</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mad_CPI">mad_CPI</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="median_ACL">median_ACL</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="mad_ACL">mad_ACL</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Middens">Middens</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Middens  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Middens  n" class="gt_row gt_right">28</td>
<td headers="Middens  mean_abundance" class="gt_row gt_right">335.41158</td>
<td headers="Middens  sd_abundance" class="gt_row gt_right">239.295619</td>
<td headers="Middens  median_CPI" class="gt_row gt_right">18.461910</td>
<td headers="Middens  mad_CPI" class="gt_row gt_right">5.44384077</td>
<td headers="Middens  median_ACL" class="gt_row gt_right">29.12240</td>
<td headers="Middens  mad_ACL" class="gt_row gt_right">0.40321519</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Surface Sediment">Surface Sediment</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Surface Sediment  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Surface Sediment  n" class="gt_row gt_right">3</td>
<td headers="Surface Sediment  mean_abundance" class="gt_row gt_right">117.31495</td>
<td headers="Surface Sediment  sd_abundance" class="gt_row gt_right">52.518303</td>
<td headers="Surface Sediment  median_CPI" class="gt_row gt_right">11.031963</td>
<td headers="Surface Sediment  mad_CPI" class="gt_row gt_right">2.61510956</td>
<td headers="Surface Sediment  median_ACL" class="gt_row gt_right">24.24743</td>
<td headers="Surface Sediment  mad_ACL" class="gt_row gt_right">0.06611670</td></tr>
    <tr><td headers="Surface Sediment  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Surface Sediment  n" class="gt_row gt_right">6</td>
<td headers="Surface Sediment  mean_abundance" class="gt_row gt_right">10.44854</td>
<td headers="Surface Sediment  sd_abundance" class="gt_row gt_right">5.074585</td>
<td headers="Surface Sediment  median_CPI" class="gt_row gt_right">9.137297</td>
<td headers="Surface Sediment  mad_CPI" class="gt_row gt_right">1.97561310</td>
<td headers="Surface Sediment  median_ACL" class="gt_row gt_right">25.92026</td>
<td headers="Surface Sediment  mad_ACL" class="gt_row gt_right">0.63028168</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Aloysia deserticola">Aloysia deserticola</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Aloysia deserticola  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Aloysia deserticola  n" class="gt_row gt_right">3</td>
<td headers="Aloysia deserticola  mean_abundance" class="gt_row gt_right">215.48935</td>
<td headers="Aloysia deserticola  sd_abundance" class="gt_row gt_right">54.049054</td>
<td headers="Aloysia deserticola  median_CPI" class="gt_row gt_right">2.103820</td>
<td headers="Aloysia deserticola  mad_CPI" class="gt_row gt_right">0.39076411</td>
<td headers="Aloysia deserticola  median_ACL" class="gt_row gt_right">28.55057</td>
<td headers="Aloysia deserticola  mad_ACL" class="gt_row gt_right">1.03106886</td></tr>
    <tr><td headers="Aloysia deserticola  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Aloysia deserticola  n" class="gt_row gt_right">3</td>
<td headers="Aloysia deserticola  mean_abundance" class="gt_row gt_right">210.95087</td>
<td headers="Aloysia deserticola  sd_abundance" class="gt_row gt_right">24.434815</td>
<td headers="Aloysia deserticola  median_CPI" class="gt_row gt_right">5.846915</td>
<td headers="Aloysia deserticola  mad_CPI" class="gt_row gt_right">0.38010692</td>
<td headers="Aloysia deserticola  median_ACL" class="gt_row gt_right">29.48836</td>
<td headers="Aloysia deserticola  mad_ACL" class="gt_row gt_right">0.06113192</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Atriplex imbricata">Atriplex imbricata</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Atriplex imbricata  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Atriplex imbricata  n" class="gt_row gt_right">8</td>
<td headers="Atriplex imbricata  mean_abundance" class="gt_row gt_right">286.81215</td>
<td headers="Atriplex imbricata  sd_abundance" class="gt_row gt_right">218.972281</td>
<td headers="Atriplex imbricata  median_CPI" class="gt_row gt_right">9.905374</td>
<td headers="Atriplex imbricata  mad_CPI" class="gt_row gt_right">3.76662109</td>
<td headers="Atriplex imbricata  median_ACL" class="gt_row gt_right">26.03645</td>
<td headers="Atriplex imbricata  mad_ACL" class="gt_row gt_right">1.45313837</td></tr>
    <tr><td headers="Atriplex imbricata  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Atriplex imbricata  n" class="gt_row gt_right">8</td>
<td headers="Atriplex imbricata  mean_abundance" class="gt_row gt_right">141.81598</td>
<td headers="Atriplex imbricata  sd_abundance" class="gt_row gt_right">75.485040</td>
<td headers="Atriplex imbricata  median_CPI" class="gt_row gt_right">18.360459</td>
<td headers="Atriplex imbricata  mad_CPI" class="gt_row gt_right">5.45399686</td>
<td headers="Atriplex imbricata  median_ACL" class="gt_row gt_right">27.49319</td>
<td headers="Atriplex imbricata  mad_ACL" class="gt_row gt_right">1.33151406</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Cristaria integerrima">Cristaria integerrima</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Cristaria integerrima  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Cristaria integerrima  n" class="gt_row gt_right">1</td>
<td headers="Cristaria integerrima  mean_abundance" class="gt_row gt_right">91.15866</td>
<td headers="Cristaria integerrima  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Cristaria integerrima  median_CPI" class="gt_row gt_right">5.796533</td>
<td headers="Cristaria integerrima  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Cristaria integerrima  median_ACL" class="gt_row gt_right">25.69106</td>
<td headers="Cristaria integerrima  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr><td headers="Cristaria integerrima  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Cristaria integerrima  n" class="gt_row gt_right">1</td>
<td headers="Cristaria integerrima  mean_abundance" class="gt_row gt_right">339.86887</td>
<td headers="Cristaria integerrima  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Cristaria integerrima  median_CPI" class="gt_row gt_right">12.427098</td>
<td headers="Cristaria integerrima  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Cristaria integerrima  median_ACL" class="gt_row gt_right">27.07403</td>
<td headers="Cristaria integerrima  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Ephedra sp.">Ephedra sp.</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Ephedra sp.  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Ephedra sp.  n" class="gt_row gt_right">2</td>
<td headers="Ephedra sp.  mean_abundance" class="gt_row gt_right">913.46960</td>
<td headers="Ephedra sp.  sd_abundance" class="gt_row gt_right">992.635678</td>
<td headers="Ephedra sp.  median_CPI" class="gt_row gt_right">12.947829</td>
<td headers="Ephedra sp.  mad_CPI" class="gt_row gt_right">5.88178808</td>
<td headers="Ephedra sp.  median_ACL" class="gt_row gt_right">27.41692</td>
<td headers="Ephedra sp.  mad_ACL" class="gt_row gt_right">0.65451011</td></tr>
    <tr><td headers="Ephedra sp.  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Ephedra sp.  n" class="gt_row gt_right">2</td>
<td headers="Ephedra sp.  mean_abundance" class="gt_row gt_right">70.36172</td>
<td headers="Ephedra sp.  sd_abundance" class="gt_row gt_right">61.312032</td>
<td headers="Ephedra sp.  median_CPI" class="gt_row gt_right">8.223281</td>
<td headers="Ephedra sp.  mad_CPI" class="gt_row gt_right">4.45716247</td>
<td headers="Ephedra sp.  median_ACL" class="gt_row gt_right">28.16296</td>
<td headers="Ephedra sp.  mad_ACL" class="gt_row gt_right">1.57494303</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Haplopappus rigidus">Haplopappus rigidus</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Haplopappus rigidus  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Haplopappus rigidus  n" class="gt_row gt_right">2</td>
<td headers="Haplopappus rigidus  mean_abundance" class="gt_row gt_right">236.03747</td>
<td headers="Haplopappus rigidus  sd_abundance" class="gt_row gt_right">278.924811</td>
<td headers="Haplopappus rigidus  median_CPI" class="gt_row gt_right">7.319356</td>
<td headers="Haplopappus rigidus  mad_CPI" class="gt_row gt_right">4.82673389</td>
<td headers="Haplopappus rigidus  median_ACL" class="gt_row gt_right">26.59827</td>
<td headers="Haplopappus rigidus  mad_ACL" class="gt_row gt_right">2.17361163</td></tr>
    <tr><td headers="Haplopappus rigidus  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Haplopappus rigidus  n" class="gt_row gt_right">4</td>
<td headers="Haplopappus rigidus  mean_abundance" class="gt_row gt_right">207.11847</td>
<td headers="Haplopappus rigidus  sd_abundance" class="gt_row gt_right">58.632182</td>
<td headers="Haplopappus rigidus  median_CPI" class="gt_row gt_right">11.599664</td>
<td headers="Haplopappus rigidus  mad_CPI" class="gt_row gt_right">2.34967561</td>
<td headers="Haplopappus rigidus  median_ACL" class="gt_row gt_right">26.27221</td>
<td headers="Haplopappus rigidus  mad_ACL" class="gt_row gt_right">1.19129699</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Jarava frigida">Jarava frigida</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Jarava frigida  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Jarava frigida  n" class="gt_row gt_right">5</td>
<td headers="Jarava frigida  mean_abundance" class="gt_row gt_right">115.10662</td>
<td headers="Jarava frigida  sd_abundance" class="gt_row gt_right">46.286095</td>
<td headers="Jarava frigida  median_CPI" class="gt_row gt_right">13.141929</td>
<td headers="Jarava frigida  mad_CPI" class="gt_row gt_right">3.20422685</td>
<td headers="Jarava frigida  median_ACL" class="gt_row gt_right">28.58114</td>
<td headers="Jarava frigida  mad_ACL" class="gt_row gt_right">0.83168444</td></tr>
    <tr><td headers="Jarava frigida  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Jarava frigida  n" class="gt_row gt_right">7</td>
<td headers="Jarava frigida  mean_abundance" class="gt_row gt_right">97.38671</td>
<td headers="Jarava frigida  sd_abundance" class="gt_row gt_right">116.663841</td>
<td headers="Jarava frigida  median_CPI" class="gt_row gt_right">13.301322</td>
<td headers="Jarava frigida  mad_CPI" class="gt_row gt_right">10.84899836</td>
<td headers="Jarava frigida  median_ACL" class="gt_row gt_right">28.85701</td>
<td headers="Jarava frigida  mad_ACL" class="gt_row gt_right">0.78851809</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Junellia seriploide">Junellia seriploide</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Junellia seriploide  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Junellia seriploide  n" class="gt_row gt_right">2</td>
<td headers="Junellia seriploide  mean_abundance" class="gt_row gt_right">375.88277</td>
<td headers="Junellia seriploide  sd_abundance" class="gt_row gt_right">333.235859</td>
<td headers="Junellia seriploide  median_CPI" class="gt_row gt_right">8.293965</td>
<td headers="Junellia seriploide  mad_CPI" class="gt_row gt_right">1.64251416</td>
<td headers="Junellia seriploide  median_ACL" class="gt_row gt_right">24.91031</td>
<td headers="Junellia seriploide  mad_ACL" class="gt_row gt_right">0.12623827</td></tr>
    <tr><td headers="Junellia seriploide  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Junellia seriploide  n" class="gt_row gt_right">2</td>
<td headers="Junellia seriploide  mean_abundance" class="gt_row gt_right">79.04812</td>
<td headers="Junellia seriploide  sd_abundance" class="gt_row gt_right">21.342944</td>
<td headers="Junellia seriploide  median_CPI" class="gt_row gt_right">11.519030</td>
<td headers="Junellia seriploide  mad_CPI" class="gt_row gt_right">2.02671942</td>
<td headers="Junellia seriploide  median_ACL" class="gt_row gt_right">28.60531</td>
<td headers="Junellia seriploide  mad_ACL" class="gt_row gt_right">0.05760277</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Nolana aplocaryoides">Nolana aplocaryoides</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Nolana aplocaryoides  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Nolana aplocaryoides  n" class="gt_row gt_right">1</td>
<td headers="Nolana aplocaryoides  mean_abundance" class="gt_row gt_right">142.39482</td>
<td headers="Nolana aplocaryoides  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Nolana aplocaryoides  median_CPI" class="gt_row gt_right">6.381062</td>
<td headers="Nolana aplocaryoides  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Nolana aplocaryoides  median_ACL" class="gt_row gt_right">25.15165</td>
<td headers="Nolana aplocaryoides  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr><td headers="Nolana aplocaryoides  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Nolana aplocaryoides  n" class="gt_row gt_right">1</td>
<td headers="Nolana aplocaryoides  mean_abundance" class="gt_row gt_right">332.41291</td>
<td headers="Nolana aplocaryoides  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Nolana aplocaryoides  median_CPI" class="gt_row gt_right">23.721943</td>
<td headers="Nolana aplocaryoides  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Nolana aplocaryoides  median_ACL" class="gt_row gt_right">28.85614</td>
<td headers="Nolana aplocaryoides  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Perityle emoryi">Perityle emoryi</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Perityle emoryi  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Perityle emoryi  n" class="gt_row gt_right">1</td>
<td headers="Perityle emoryi  mean_abundance" class="gt_row gt_right">789.95012</td>
<td headers="Perityle emoryi  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Perityle emoryi  median_CPI" class="gt_row gt_right">14.463342</td>
<td headers="Perityle emoryi  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Perityle emoryi  median_ACL" class="gt_row gt_right">28.92927</td>
<td headers="Perityle emoryi  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Sp2">Sp2</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Sp2  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Sp2  n" class="gt_row gt_right">1</td>
<td headers="Sp2  mean_abundance" class="gt_row gt_right">227.98959</td>
<td headers="Sp2  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Sp2  median_CPI" class="gt_row gt_right">14.979941</td>
<td headers="Sp2  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Sp2  median_ACL" class="gt_row gt_right">24.10160</td>
<td headers="Sp2  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr><td headers="Sp2  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Sp2  n" class="gt_row gt_right">1</td>
<td headers="Sp2  mean_abundance" class="gt_row gt_right">407.16792</td>
<td headers="Sp2  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Sp2  median_CPI" class="gt_row gt_right">56.383496</td>
<td headers="Sp2  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Sp2  median_ACL" class="gt_row gt_right">29.00538</td>
<td headers="Sp2  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Sp3">Sp3</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Sp3  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Sp3  n" class="gt_row gt_right">1</td>
<td headers="Sp3  mean_abundance" class="gt_row gt_right">231.15961</td>
<td headers="Sp3  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Sp3  median_CPI" class="gt_row gt_right">8.105427</td>
<td headers="Sp3  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Sp3  median_ACL" class="gt_row gt_right">28.57253</td>
<td headers="Sp3  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr><td headers="Sp3  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Sp3  n" class="gt_row gt_right">1</td>
<td headers="Sp3  mean_abundance" class="gt_row gt_right">184.31794</td>
<td headers="Sp3  sd_abundance" class="gt_row gt_right">NA</td>
<td headers="Sp3  median_CPI" class="gt_row gt_right">9.483458</td>
<td headers="Sp3  mad_CPI" class="gt_row gt_right">0.00000000</td>
<td headers="Sp3  median_ACL" class="gt_row gt_right">28.20043</td>
<td headers="Sp3  mad_ACL" class="gt_row gt_right">0.00000000</td></tr>
    <tr class="gt_group_heading_row">
      <th colspan="8" class="gt_group_heading" scope="colgroup" id="Tiquilia atacamensis">Tiquilia atacamensis</th>
    </tr>
    <tr class="gt_row_group_first"><td headers="Tiquilia atacamensis  wax" class="gt_row gt_center">FAMEs</td>
<td headers="Tiquilia atacamensis  n" class="gt_row gt_right">3</td>
<td headers="Tiquilia atacamensis  mean_abundance" class="gt_row gt_right">107.77041</td>
<td headers="Tiquilia atacamensis  sd_abundance" class="gt_row gt_right">53.135379</td>
<td headers="Tiquilia atacamensis  median_CPI" class="gt_row gt_right">9.943925</td>
<td headers="Tiquilia atacamensis  mad_CPI" class="gt_row gt_right">0.03941876</td>
<td headers="Tiquilia atacamensis  median_ACL" class="gt_row gt_right">22.93231</td>
<td headers="Tiquilia atacamensis  mad_ACL" class="gt_row gt_right">0.47453506</td></tr>
    <tr><td headers="Tiquilia atacamensis  wax" class="gt_row gt_center">n-Alkanes</td>
<td headers="Tiquilia atacamensis  n" class="gt_row gt_right">3</td>
<td headers="Tiquilia atacamensis  mean_abundance" class="gt_row gt_right">89.80569</td>
<td headers="Tiquilia atacamensis  sd_abundance" class="gt_row gt_right">30.591602</td>
<td headers="Tiquilia atacamensis  median_CPI" class="gt_row gt_right">8.440672</td>
<td headers="Tiquilia atacamensis  mad_CPI" class="gt_row gt_right">0.61098165</td>
<td headers="Tiquilia atacamensis  median_ACL" class="gt_row gt_right">28.96094</td>
<td headers="Tiquilia atacamensis  mad_ACL" class="gt_row gt_right">0.16799931</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="8">TA [ug/gdw]; Total Abundance</td>
    </tr>
    <tr>
      <td class="gt_sourcenote" colspan="8">TA mad; median absolute deviation form Total Abundance</td>
    </tr>
  </tfoot>
  
</table>
</div>
</div>
</div>
</section>
<section id="n-alkane-and-plant-macrofossil-from-rodent-middens-in-the-atacama-desert-over-the-last-17000-years" class="level2">
<h2 class="anchored" data-anchor-id="n-alkane-and-plant-macrofossil-from-rodent-middens-in-the-atacama-desert-over-the-last-17000-years">n-Alkane and plant macrofossil from rodent middens in the Atacama Desert over the last 17,000 years</h2>
<p>A total of sixteen different plant taxa were identified covering twelve families; fifteen genera and five species of plant macrofossils (Table 2). Radiocarbon ages from 28 rodent middens reveal a temporal coverage for the last 17 ka cal BP (Table 3). Fecal pellets indicate that the middens were either made mainly by the ashy chinchilla rat (Abrocoma cinerea) and by leaf-eared mice (Phyllotis spp.). In the modern midden 208-B (150 ± 90 cal yr BP at 3592 m a.s.l., south slope; Table 3) we find macro-remains of Haplopappus sp., Junellia bryoides, Gilia sp., Cistanthe sp., Phacelia cumingii, Phacelia pinnatifida, Cryptantha sp. and Ephedra americana —a composition similar to the species collected in the field (Haplopappus sp., Junellia bryoides, Gilia sp., Cistanthe sp., Phacelia cumingii, Phacelia pinnatifida, Cryptantha sp. and Ephedra americana besides Maihueniopsis sp., Baccharis tola and Pappostipa frígida). Among taxa identified at the site, we note that some are quite scarce and slope exclusivities, such as Maihueniopsis sp and Baccharis Tola on the north slope and Pappostipa frígida on the south slope.</p>
<div id="figure-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/Fig_2.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Abundance and distribution of leaf waxes (n-alkanoic acids and n-alkanes) along an environmental gradient in the Atacama Desert (Coast, Hyperarid Desert, Pre-Puna, Puna, Steppe and superficial lacustrine sediments of two high Andean steppe lakes). (a) Average Chain Length (ACL), (b) Carbon Preference Index (CPI), (c) Total Abundances and (d) percentage distribution of long-chain of leaf waxes from twelve species of Atacama Desert.</figcaption><p></p>
</figure>
</div>
<table class="table">
<caption>Macrofossils identified, including their family, type and phytogeographic affinity.</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<tbody>
<tr class="odd">
<td>Taxa</td>
<td>Family</td>
<td>Type</td>
<td>Phytogeographic affinity</td>
</tr>
<tr class="even">
<td>Malvaceae</td>
<td>Malvaceae</td>
<td>--</td>
<td>--</td>
</tr>
<tr class="odd">
<td>Chenopodiaceae</td>
<td>Chenopodiaceae</td>
<td>--</td>
<td>--</td>
</tr>
<tr class="even">
<td>Baccharis aff. tola*</td>
<td>Asteraceae</td>
<td>Shrub</td>
<td>Puna</td>
</tr>
<tr class="odd">
<td>Haploppapus sp.</td>
<td>Asteraceae</td>
<td>--</td>
<td>Dessert</td>
</tr>
<tr class="even">
<td>Cryptantha sp.</td>
<td>Boraginaceae</td>
<td>Annual</td>
<td>Prepuna</td>
</tr>
<tr class="odd">
<td>Brassicaceae aff. Atacama nivea*</td>
<td>Brassicaceae</td>
<td>--</td>
<td>Dessert</td>
</tr>
<tr class="even">
<td>Ephedra americana</td>
<td>Ephedraceae</td>
<td>Shrub</td>
<td>Puna and Prepuna</td>
</tr>
<tr class="odd">
<td>Adesmia sp.</td>
<td>Fabeceae</td>
<td>Annual and perennial herbs</td>
<td>Puna and Prepuna</td>
</tr>
<tr class="even">
<td>Phacelia cuminingii</td>
<td>Hydrophyllaceae</td>
<td>Annual herbs</td>
<td>Puna and Prepuna</td>
</tr>
<tr class="odd">
<td>Phacelia pinnatifida</td>
<td>Hydrophyllaceae</td>
<td>Annual and perennial herbs</td>
<td>Prepuna</td>
</tr>
<tr class="even">
<td>Cristaria sp.</td>
<td>Malvaceae</td>
<td>Annual</td>
<td>Puna and Prepuna</td>
</tr>
<tr class="odd">
<td>Pappostipa frigida</td>
<td>Poaceae</td>
<td>Perennial Grass</td>
<td>Steppa</td>
</tr>
<tr class="even">
<td>Gillia sp.</td>
<td>Polemoniaceae</td>
<td>Annual</td>
<td>Puna and Prepuna</td>
</tr>
<tr class="odd">
<td>Cistanthe sp.</td>
<td>Portulacaceae</td>
<td>Perennial Grass</td>
<td>Prepuna</td>
</tr>
<tr class="even">
<td>Fabiana sp.</td>
<td>Solaneaceae</td>
<td>Perennial Grass</td>
<td>Puna</td>
</tr>
<tr class="odd">
<td>Junellia bryoides</td>
<td>Verbebaceae</td>
<td>Shrub</td>
<td>Puna</td>
</tr>
</tbody>
</table>
<p>A diagram of the relative abundances of each taxon along the chronology obtained with AMS 14C dating (Table 3) is shown in Figure 3. Fecal-pellet 𝛿13C values show a range from -21.3 to -25,4 ‰ with a median of -23 ‰. The middens were dominated by the local taxa Junellia bryoides, Cistanthe sp., Ephedra americana and Phacelia cumingii. At ca. 17 ka cal BP, the record shows the presence of only two local taxa (Junellia bryoides and Phacelia pinnatifida) and one extra-local taxa (Adesmia sp.). Between ca. 15.5 and 10 ka cal BP, the record shows an increase in local plant richness and extra-local species such as Stipa frígida, Adesmia sp, Malvaceae, Chenopodiaceae, Baccharis aff tola and Brassicaceae aff Atacamanivea. A great group of middens between ca. 10 and 3 ka cal BP shows a decrease in plant richness with an increase in the annual extra-local Malvaceae family. From 3 to 0.18 ka cal BP, there are increases in the local taxa richness dominated by Junellia bryoides and Cistante sp. with the appearance of Haplopappus sp. and Cryptantha sp., among others.</p>
<table class="table">
<caption>Site location, radiocarbon dates, calendar year BP (95.4% probability ranges; curve Shcal20, Oxcal 4.4) and former agent for 28 rodent middens analyzed (see Fig. 1 for midden localities). *:Unidentified</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;">ID</td>
<td style="text-align: center;">Age</td>
<td style="text-align: center;">sd</td>
<td style="text-align: center;">Lower cal yr BP</td>
<td style="text-align: center;">Upper cal yr BP</td>
<td style="text-align: center;">sd</td>
<td style="text-align: center;">median</td>
<td style="text-align: center;">lat</td>
<td style="text-align: center;">long</td>
<td style="text-align: center;">Midden agent</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN208A</td>
<td style="text-align: center;">1310</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">1270</td>
<td style="text-align: center;">1115</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">1230</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN208B</td>
<td style="text-align: center;">180</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">280</td>
<td style="text-align: center;">modern</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN211</td>
<td style="text-align: center;">8210</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">9270</td>
<td style="text-align: center;">9010</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">9105</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN213</td>
<td style="text-align: center;">12855</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">15505</td>
<td style="text-align: center;">15145</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">15300</td>
<td style="text-align: center;">25.599</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN214A</td>
<td style="text-align: center;">14150</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">17350</td>
<td style="text-align: center;">17040</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">17185</td>
<td style="text-align: center;">25.599</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN214B</td>
<td style="text-align: center;">10175</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11875</td>
<td style="text-align: center;">11635</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">11780</td>
<td style="text-align: center;">25.599</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN214C</td>
<td style="text-align: center;">12920</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">15575</td>
<td style="text-align: center;">15245</td>
<td style="text-align: center;">85</td>
<td style="text-align: center;">15400</td>
<td style="text-align: center;">25.599</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN215A</td>
<td style="text-align: center;">5700</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">6540</td>
<td style="text-align: center;">6315</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">6440</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN215B</td>
<td style="text-align: center;">1740</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">1700</td>
<td style="text-align: center;">1535</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">1600</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN215C</td>
<td style="text-align: center;">3515</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">3835</td>
<td style="text-align: center;">3645</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">3755</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.2429</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN216</td>
<td style="text-align: center;">7895</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">8775</td>
<td style="text-align: center;">8545</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">8635</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.23</td>
<td style="text-align: center;">Phyllotis</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN2171</td>
<td style="text-align: center;">8615</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">9660</td>
<td style="text-align: center;">9480</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">9540</td>
<td style="text-align: center;">25.596</td>
<td style="text-align: center;">69.22</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN2172</td>
<td style="text-align: center;">8980</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">10215</td>
<td style="text-align: center;">9905</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">10060</td>
<td style="text-align: center;">25.596</td>
<td style="text-align: center;">69.22</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN218</td>
<td style="text-align: center;">11035</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">13070</td>
<td style="text-align: center;">12795</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">12925</td>
<td style="text-align: center;">25.595</td>
<td style="text-align: center;">69.235</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN219</td>
<td style="text-align: center;">10480</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">12605</td>
<td style="text-align: center;">12095</td>
<td style="text-align: center;">135</td>
<td style="text-align: center;">12345</td>
<td style="text-align: center;">25.594</td>
<td style="text-align: center;">69.235</td>
<td style="text-align: center;">Phyllotis</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN220A</td>
<td style="text-align: center;">9190</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">10485</td>
<td style="text-align: center;">10230</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">10300</td>
<td style="text-align: center;">25.594</td>
<td style="text-align: center;">69.235</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN237A</td>
<td style="text-align: center;">2140</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">2115</td>
<td style="text-align: center;">2005</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">2065</td>
<td style="text-align: center;">25.594</td>
<td style="text-align: center;">69.235</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN237B</td>
<td style="text-align: center;">1120</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">1055</td>
<td style="text-align: center;">925</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">970</td>
<td style="text-align: center;">25.593</td>
<td style="text-align: center;">69.231</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN238</td>
<td style="text-align: center;">9565</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11075</td>
<td style="text-align: center;">10690</td>
<td style="text-align: center;">125</td>
<td style="text-align: center;">10865</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN242</td>
<td style="text-align: center;">11705</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">13600</td>
<td style="text-align: center;">13455</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">13535</td>
<td style="text-align: center;">25.6</td>
<td style="text-align: center;">69.24</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN243A</td>
<td style="text-align: center;">10015</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11625</td>
<td style="text-align: center;">11265</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">11450</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN2451</td>
<td style="text-align: center;">11950</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">14010</td>
<td style="text-align: center;">13605</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">13775</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN2452</td>
<td style="text-align: center;">9125</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">10340</td>
<td style="text-align: center;">10185</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">10235</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN246</td>
<td style="text-align: center;">10200</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11925</td>
<td style="text-align: center;">11650</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">11810</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.238</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN249B</td>
<td style="text-align: center;">4230</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">4845</td>
<td style="text-align: center;">4585</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">4730</td>
<td style="text-align: center;">25.597</td>
<td style="text-align: center;">69.239</td>
<td style="text-align: center;">*</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN256</td>
<td style="text-align: center;">345</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">445</td>
<td style="text-align: center;">305</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">395</td>
<td style="text-align: center;">25.593</td>
<td style="text-align: center;">69.231</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">QIN259</td>
<td style="text-align: center;">10105</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">11765</td>
<td style="text-align: center;">11325</td>
<td style="text-align: center;">125</td>
<td style="text-align: center;">11635</td>
<td style="text-align: center;">25.594</td>
<td style="text-align: center;">69.234</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">QIN260A</td>
<td style="text-align: center;">1740</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">1700</td>
<td style="text-align: center;">1535</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">1600</td>
<td style="text-align: center;">25.593</td>
<td style="text-align: center;">69.232</td>
<td style="text-align: center;">Abrocoma</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>The rodent middens contain high wax values spread with a total mean n-alkanes abundance of 335.4 +/- 239 ug/g dw (n=24, CPI_median = 18.46 +/- 5.44; ACL_median = 29.12 +/- 0.4, Table 1 and Figure 4). The chain-length distribution in middens was between n-C21 and n-C35 with a higher abundance of n-C27 to n-C31 chain and predominance of carbon length chain n-C29. The palaeomidden dated to ca. 17 ka cal BP showed a lower abundance in all chain-length distributions. One of the main features of the middens dated to ca. 15.2 ka cal BP and between 14 and 12 ka cal BP was the high n-alkane abundance of longer chains (n-C25 to n-C35) compared to the chain-length abundance between ca. 11 and 5 ka cal BP. The abundances of n-alkane for the youngest samples dated between 5 and 0.18 ka cal BP shows an increase in all chain-length distribution, where the midden with higher n-alkanes abundance was at ~ 4 ka cal BP (Figure 3). Remarkably, the midden dated at 11.7 ka cal BP has the highest concentration of n-alkanes in the record (~1,000 ug/g dw), where the carbon length chain n-C29 dominates. Two grass samples, dated between 970 (QIN237-B) and 11,780 (QIN 214b) ka cal BP, extracted from the palaeomiddens matrix showed high n-alkane values.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig_3.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Abundance of n-alkanes (µg/g dw) and 𝛿13C, 𝛿15N and C/N ratio values from fecal-pellet obtained of the palaeomiddens from Quebrada Incahuasi. A constrained cluster analysis by the method of incremental sum of squares (CONISS) was performed to see the relationships between the samples.</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="distribution-of-leaf-wax-n-alkanes-and-n-alkanoic-acids-along-an-altitudinal-transect-504200-m-a.s.l-in-the-atacama-desert" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-leaf-wax-n-alkanes-and-n-alkanoic-acids-along-an-altitudinal-transect-504200-m-a.s.l-in-the-atacama-desert">Distribution of leaf wax n-alkanes and n-alkanoic acids along an altitudinal transect (50–4200 m a.s.l) in the Atacama Desert</h2>
<p>Several studies have characterized the relationship between leaf wax concentrations and environmental variables along elevational gradients as an approach to understanding past climatic changes (Cerda-Peña et al., 2020; DeLucia and Berlyn, 2011; Feakins et al., 2016; Jansen et al., 2006; Nieto-Moreno et al., 2016; Shepherd and Wynne Griffiths, 2006). The leaf wax n-alkanes and n-alkanoic acids along the vegetational transect in the Atacama desert show a species-specific and heterogeneous distribution in the chain lengths (Figures 1 and 2). Leaf waxes from Steppe and Puna species have a clear predominance of n-C29/n-C28 chain lengths in n-alkane and fatty acid, respectively. On the other hand, the Prepuna showed a higher abundance on n-C27/n-C26 chain lengths followed by n-C29/n-C28, n-C31/n-C30 and n-C25, respectively. At the coast —where advected fog plays an important role as a moisture source — we found equal abundance of n-C29 and n-C27, while the plants from the Hyperarid Desert showed two different and antagonistic wax distributions where predominate n-alkane n-C31 and a higher n-alkanoic acids abundances of medium chain lengths, as n-C22 followed by n-C26 and n-C24 (Figure 2). Long (how long???) n-alkane chain lengths may be produced by high temperature and low moisture conditions (Dodd et al., 1998; Feakins and Sessions, 2010; Hoffmann et al., 2013). Mörchen et al., 2021 found in ten plant species of the Atacama Desert that the n-alkanes abundance showed a predominance of chain lengths n-C27 and n-C31. These authors related the higher n-alkane production to the influence of the sources of moisture coming either from coastal fog or summer precipitation in the Andes. Contreras et al., 2022 provide a detailed assessment of leaf waxes from Tillandsia landbeckii (a CAM specie highly specialized to living only off fog), describing a homogeneous n-alkanes distribution that ranges between n-C23 and n-C31 where the leaf wax distribution (ACL and CPI index) showed a high inverse correlation with moisture availability. In the northwestern slope of the south-central Andes of Argentina, n-alkanes in soil show a higher abundance and unimodal distribution along an altitudinal transect of the chain lengths n-C27, n-C33 and n-C29 (Nieto-Moreno et al., 2016). While the tropical forest from Kosñipata valley in Perú, (Feakins et al., 2016) showed a predominance of n-C29 and nC31 chains followed by n-C27 and a poor relationship between temperature and leaf wax distribution. Wu et al.&nbsp;(2019), in another elevation gradient between the Amazon floodplain and the eastern flank of the Andes in Peru, found a dominance of chain lengths n-C29 and n-C31 with a higher n-C31/n-C29 ratio at lower elevation sites. Teunissen van Manen et al., 2020 observe this same relationship in leaves and soil in Ecuador. All these studies above show that the proportions in the chain lengths of n-alkane are highly variable at ecosystem-dependent scale.</p>
<p>Compared to other deserts, most of the plants in the south-central Atacama landscapes incorporate atmospheric CO2 through the C3 photosynthetic pathway —although there are several CAM species (Ehleringer et al., 1998). Only a few perennial shrubs and summer annual herbs C4 grow in higher temperature and moisture zones. In the Steppe, species composition was mainly of the Poaceae family, dominated by Pappostipa frigida which shows high leaf waxes abundance of chain length n-C28/n-C29 and n-C30/n-C31 (Figure 1S). Diefendorf and Freimuth (2017) describe in C3 graminoid that the dominant n-alkane was n-C31, followed by n-C33 and n-C29. In fact, n-alkanes on Pappostipa sp. leaves contained inside the matrix from two rodent middens (dated to 970 and 11780 cal yr BP) also showed much higher abundances of n-C29 —consistent with what is observed in modern samples (Figure 2). In the Puna, in addition to P. frigida, the landscape was dominated by the species H. rigidus and J. seriphioides containing high n-alkane abundances of n-C25/n-C28 and n-C21/n-C22, respectively (Figure 1S) and in the Prepuna, the species Atriplex imbricata (Amaranthaceae), Aloysia deserticola and Haplopappus rigidus are found. The C4 sub-shrub A. imbricata showed a wide distribution along the altitudinal gradient (between 1,700 and 3,200 m asl) and higher abundances of n-C28/n-C27 chain length followed by n-C24/n-C25, n-C28/n-C29 and n-C30/n-C31 (Figure 1S). In addition, the total abundance of n-alkanes in A. imbricata significantly correlates with elevation (p &lt; 0.001; R2= 0.8, Figure 2S). In Africa, Australia, and North America, C4 plants show much higher abundances of the alkanes n-C29, n-C31 and n-C33 (Carr et al., 2014; Feakins et al., 2016; Garcin et al., 2014; Howard et al., 2018; Vogts et al., 2009). A. deserticola contains a higher abundance of n-alkane n-C31 followed by n-C29, and in general, shows lower abundances of n-alkanoic acids compared to n-alkanes. H. rigidus shows a higher abundance of n-C25. In the hyperarid desert, we found only two species, T. atacamensis and A. imbricata. T. atacamensis showed a clear dominance of n-C22/n-C29. This asymmetric distribution between n-alkanes and n-alkanoic acids chain length abundances could be a structural adaptation to extreme aridity —generating higher abundances of short- and medium- n-alkanoic acids chain length as precursors to other aliphatic compounds of cuticular waxes— thereby favoring hydrophobic conditions that reduce water loss (Bush and McInerney, 2013; Contreras et al., 2022; Macková et al., 2013; Shepherd and Wynne Griffiths, 2006). On the coast, C. integerrima and N. aplocaryoides were the dominant species with chain lengths of n-C27 and n-C29, respectively. However, in the field, we found low species abundance and richness. These data generally support the idea that the dominant n-alkane chain abundances have strong species-specific chemotaxonomic signatures (Cerda-Peña et al., 2020).</p>
</section>
</section>
<section id="distribution-of-leaf-wax-n-alkanes-and-n-alkanoic-acids-in-the-atacama-desert" class="level1">
<h1>Distribution of leaf wax n-alkanes and n-alkanoic acids in the Atacama Desert</h1>
<p>Biotic and abiotic stresses can induce metabolic and biosynthesis responses in cuticular waxes (Lewandowska et al., 2020; Shepherd and Wynne Griffiths, 2006). In the Atacama Desert, one of the harshest terrestrial environment conditions on earth, n-alkanes and n-alkanoic acids from leaf-wax show a strong relationship to vegetation belts (Figure 1). We observed a higher total abundance of individual chains of n-alkane and fatty acid in zones where the plants have more moisture available coming from the coast and seasonal summer rains (Arroyo et al., 1988; Díaz et al., 2019). Atacama vegetation is adapted to prolonged drought conditions, mechanical stress, low nutrient availability, and high levels of radiation, salinity, and metals along the altitude gradient (Arroyo et al., 1999; Díaz et al., 2016; Eshel et al., 2021; Rondanelli et al., 2015). Several studies show significant correlations between n-alkanes distributions with temperature and precipitation (Bush and McInerney, 2015; Feakins et al., 2016; Hoffmann et al., 2013; Tipple and Pagani, 2013; Wang et al., 2018), while others show a weak or null relationship with climatic variables (Carr et al., 2014; Howard et al., 2018). The n-alkane distributions along the transect also suggest a high relationship with the available moisture conditions in the vegetation floors that should be evaluated before using the leaf waxes as an indicator of paleoenvironmental changes. Morchen et al., (2021) and Contreras et al., (2021), argue that n-alkanes from fog-fed plants in the Atacama that receive moisture from the coast show a dominance of n-C31, n-C29, n-C33 and n-C27 chain lengths, while plants affected by summer rains show a greater abundance of n-C31 and n-C29 chain lengths.</p>
</section>
<section id="source-n-alkane-leaf-wax-in-a-17000-yr-rodent-midden-record-from-atacama-desert" class="level1">
<h1>Source n-alkane leaf wax in a 17,000 yr rodent midden record from Atacama Desert</h1>
<p>The analysis of n-alkanes in rodent coprolites from middens showed a marked distribution range of chain length between n-C21 and n-C35 with a greater abundance of n-C29 followed by n-C31 (Figure 3). These waxes distribution were similar to that found in the plants that dominate the Steppe and Puna, where species such as Pappostipa frigida, Haplopappus rigidus and Junellia seriphioides have a greater abundance of n-C27, n-C29 and n-C31. In the Steppe, where Pappostipa frigida dominates the landscape, the fingerprint of chain length is the n-C29. When we compared the n-alkanes from grasses inside two rodent middens matrix with the n-alkanes obtained from their fecal-pellet (QIN237-B and QIN214-B; 970 and 11,780 a cal BP, respectively), we noted a similar pattern between their distributions, but with concentrations that are one to two orders of magnitude lower —50/16 [ug/g dw] in grasses compared to 368/1054 [ug/g dw] in fecal-pellet (Figure 5S). Latorre et al., 2002, studied the relationship between vegetation and dietary behavior by analyzing cuticles in feces from 41 rodent middens during the last 45 ka cal BP of the prepuna of the Atacama Desert. This comparative study between plant macrofossil, abundance of grasses and leaf wax analysis showed as the diet of different rodent species are closely related to the surrounding vegetation, however, we can not rule out that the dietary preferences and collecting behaviors can introduce bias into midden records (Borrelli and Holmgren, 2016). Our fecal-pellet isotopic analysis shows 𝛿13C values close to -23 ‰ that are indicative of an almost pure C3 diet (Latorre et al., 2002a). This is consistent with our RDA analysis between abundance of plant macrofossil and n-alkanes which discriminate between the abundance n-C29 and plant extralocal of Prepuna taxa together with n-C31 (Figure 6S). Based on our observations, we hypothesize that the greater abundance of plant species in the landscape, greater will be the chain length variations in the middens and during greater grasses abundance we will observe a dominance of n-C29. This is due to the species-specific chemotaxonomic biomarkers and the dietary generalist behavior of rodents (Borrelli and Holmgren, 2016; Latorre et al., 2002a).</p>
<section id="leaf-wax-n-alkane-in-rodent-midden-record-as-proxy-of-palaeoenvironmental-changes" class="level2">
<h2 class="anchored" data-anchor-id="leaf-wax-n-alkane-in-rodent-midden-record-as-proxy-of-palaeoenvironmental-changes">Leaf wax n-alkane in rodent midden record as proxy of palaeoenvironmental changes</h2>
<p>Paleomidden records from the central Atacama (15° to 27°S), contain many extra-local species indicative of past pluvials in the south-central Andes during the Quaternary (Betancourt et al., 2000; Díaz et al., 2012, 2019; Jara et al., 2020, 2022; Latorre et al., 2002a, 2003; Mujica et al., 2015). At least six pluviometric anomalies have been linked with vegetation changes in the Atacama; CAPE I (ca. 18 to 14.8 ka cal BP), CAPE II (ca. 13.0 to 8.6 and 8.1 to 7.6 ka cal BP) and four relatively short-period during ~ 4 to 3.4, ~2.5, MCA (ca. 1.2 and 0.8 ka cal BP) and LIA (ca. 0.5 and 0.1 ka cal BP). Low latitude insolation changes and/or strengthening/weakening of the South American Monsoon System and precipitation from the maritime weather system —forced by ocean-atmosphere dynamics of the Pacific and/or Atlantic— are the most common climatic teleconnections proposed tot explain these precipitation anomalies (Betancourt et al., 2000; Gayo et al., 2012; González-Pinilla et al., 2021; Houston and Latorre, 2022; Jara et al., 2022; Latorre et al., 2006; Rech et al., 2002).</p>
<p>Can the n-alkanes obtained from paleomiddens records reflect niche shifts in the Atacama plant communities during the past? The leaf wax n-alkane chain-length distributions of the plants studied show a clear species-specific molecular signature associated with the different vegetational belts (Figure 1S). High Andean Steppes from Atacama are represented mainly by n-C29 and n-C31 n-alkanes. At the same time, environments in lowlands (prepuna and puna) are characterized by a greater diversity of chain lengths between n-C22 to n-C33 due to the different species that live there. These molecular relationships could be used to detect wax input due to extra-local species in ancient Atacama ecosystems. In that regard, rodent paleomiddens can be an excellent tool to understand the relationships between wax production and plant species that lived at a given time. Plant macrofossils analysis from modern middens dated around 150 cal a BP (3,592 m asl, Figure 3) from pre-puna showed a composition similar to the species collected in the field (Haplopappus sp, Junellia bryoides, Gilia sp, Cistanthe sp, Phacelia cumingii, Phacelia pinnatifida, Cryptantha sp. and Ephedra americana). In the same manner, as observed in the puna and pre-puna, the n-alkane chain lengths obtained from fecal pellets in this modern midden are dominated by n-C25, n-C27 and n-C33 whereas n-C29 and n-C31 are co-dominants. Furthermore, when we analyze the n-alkane distributions throughout all paleomiddens, the data show a high n-alkane chain length variability over the last 17 ka cal BP (Figure 4). We propose that these heterogeneous n-alkane distributions represent a response to changes in the climate and species composition of the pre-puna where the paleomiddens are generated. That idea is supported by the Redundancy analysis (RDA) where the extra-local species are grouped with n-C25, n-C27 and n-C29 n-alkanes (Figure 6S) and by the linked between the n-alkene distributions of grasses and fecal pellets found in the middens QIN237-B and QIN214-B (Figure 5S). This suggests that the Atacama Desert plants have a sufficiently high molecular plasticity to overrun ecosystems different from the current, as shown by some recent studies in these extreme habitats (Díaz et al., 2019; Dussarrat et al., 2022; Eshel et al., 2021). To test this assumption, we compare our n-alkanes paleomidden series with different climate change records associated with food variations in the Atacama Desert (Figure 6).</p>
<p>During the CAPE I, paleomidden records show an increase of extra-local species, together with n-C25, n-C27, n-C31 and n-C33 n-alkanes (Figure 5 and 6a-d). According to the current distribution of chain lengths in the Atacama Desert, this increase could represent greater biodiversity of plants from different vegetation belts. González-Pinilla et al., 2021, reconstructs positive mean annual rainfall (MAR) anomalies in the Atacama Desert at 15.9 to 14.8 ka cal BP (MAR = 142 ± 10), 13.0 to 8.6 ka B.P (MAR = 130 ± 18) and more variable precipitation during the Late Holocene (Figure 6f). They liked the MAR anomalies from CAPE I to the Heinrich Event 1 (HE-1) and La Niña-like conditions inferred from El Niño flood activity record in Peru (Rein et al., 2005) that drove an intensification and southward shift of the SASM. These moisture changes are coeval with those observed in the n-alkanes of the midden series (Figure 6f). In contrast, in the western Central Andes lake records (Figure 6h-g), were observed low levels of lakes Miscanti, Chungará and Junín during this phase, which have been associated with the weakening of the South American Summer Monsoon (SASM) and the hydrological balance of the upper Amazon basin and the Altiplano (Grosjean et al., 2001; Moreno et al., 2007; Rodbell et al., 2022; Sáez et al., 2007; Valero-Garcés et al., 1996). During the CAPE II, the n-alkenes show an initial increase in n-C31 chain length followed by an abrupt increase in n-C29 during the end of the YD (at ca. 17.780 ka cal BP) followed by fluctuations of the n-C27 n-alkane (Figure 6). Between the CAPE I and CAPE II phases (ca. 14.8 and 13.1 ka B.P.), the decrease of n-alkenes are indicative of dry conditions that coincide with the Bölling/Allerød (BA) warming period and the meltwater pulse 1a (MWP-1A) occurred around 14.6 ka (Deschamps et al., 2012; He and Clark, 2022; Liu et al., 2009; Obase and Abe-Ouchi, 2019; Thiagarajan et al., 2014). These data supports the assumption of a very dry period by González-Pinilla et al., 2021 between 14.8 and 13.1 ka B.P. However, high lake levels in the western central Andes (Figure 6g-f) during this period suggest a seesaw response of SASM by an abrupt increase of the AMOC (Figure 6j). This apparent disagreement could be explained by different sources of oceanic and continental moisture along the Andean Dry Diagonal (Houston and Latorre, 2022), where ENSO-like conditions could play a preponderant role. Stable deuterium and carbon isotope analysis of individual long-chain n-alkanes from paleomiddens could give us clues about the mechanisms at work in the Atacama Desert. In the Middle Holocene, the palemiddens record shows a greater abundance of n-C29 and n-C27 chain lengths typical of grasses, while during the late Holocene the differences in abundances among the n-alkanes decrease. Several authors have described the aridity conditions in the Atacama Desert during the Middle Holocene (Betancourt et al., 2000; Grosjean and Núñez, 1994; Nunez, 2002; Valero-Garcés et al., 1996), the timing and lapse of this aridity condition is still under discussion (Grosjean, 2001; Grosjean et al., 2003; Latorre et al., 2002b; Rech et al., 2003, 2002), where La Niña-like conditions and a spatial complexity of precipitation of SASM system are the main characteristics (Brierley et al., 2020; Chen et al., 2016; Olson et al., 2020; Rein et al., 2005; Wong et al., 2021). Finally, during the late Holocene the n-alkane chain lengths are co-dominant and represent the present-day plant communities, where climatic variability could only partly explain the distributions of the more present-day chain lengths if we consider other factors such as species introduction by human activity.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Fig_5.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Comparison of selected n-alkane abundances (µg/g dw) and macrofossil obtained from paleomiddens records with representative local, regional and global paleoclimate records. (a) total number of extra-local species of macrofossil from paleomiddens in Quebrada Incahuasi. (b) Average Chain Length (ACL) of n-alkanes. (c-e) C27, C29 and C31 n-alkane abundances (µg/g dw). (f) MAR anomalies in the central Atacama Desert (González-Pinilla et al., 2021). (g) Miscanti ancient lake level (Valero-Garcés et al., 1996); 23º44’S, 67º46’W, 4140 m asl). (i) Late Pleistocene-Holocene El Niño-like ENSO-sensitive marine records, from Peruvian shelf (Rein et al., 2005). (j) Transient simulation of precipitation (TraCE 21k-II, (He and Clark, 2022) over the central Atacama (24°S). From (a) to (f), the age-uncertainty median ensemble (estimated with the Banded Age Model in GeochronR package) is shown in black, with the 50% and 95% highest-density probability ranges shown in dark and light gray, respectively. (see Comboul et al., 2014; McKay et al., 2021 for more detail). OD: Oldest Dryas, BA: Bølling-Allerød, YD: Younger Dryas Stadial.</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<p>This work demonstrates how the abundance of leaf waxes and climate change obtained from paleomiddens are related to vegetation change in the Atacama. The n-alkanes and n-alkanoic acids from current plant leaf waxes show a high variability through the elevational gradient and a species-specific molecular signature of these vegetational belts. The Steppe is characterized by high abundances of n-C29 chain long followed by n-C31, n-C27, respectively. Leaf waxes from the Puna and Pre-puna have a greater abundance and diversity of chain lengths, whereas in the absolute desert the most abundant n-alkanes and n-alkanoic acids were the n-C31 and n-C22 chains. Along the coastal Atacama, the n-alkanes that predominated were n-C27 and n-C29 in contrast with a decrease of the n-alkanoic acids that were dominated by n-C28 and n-C26 chains. We observe a decoupling of leaf wax ACL values between n-alkanes and n-alkanoic acids in the absolute desert. Biochemical differences between n-alkanes and n-alkanoic acids ACL values could imply different hydric-deficit tolerance strategies in plants under hyper-extreme environmental conditions. In general, our study shows that paleomiddens are an excellent proxy of leaf wax abundances in the Prepuna of the Atacama and respond to different moisture pulses previously identified in the region. As described in other works, the paleomidden record indicates increased wet conditions during the CAPE phases consistent with lower summer insolation and increased humidity modulated by ENSO and SASM. Furthermore, paleomiddens show a dry period between ca. 13 and 14.8 ka cal BP co-occurring during a strengthened AMOC and abrupt increase in grasses at 11.7 ka cal BP as indicated by increased n-C29 chain long. Lower bioproductivity could be interpreted during the Early and Middle Holocene (from ca. 11.0 to 6.0 ka cal BP), coincident with a decrease in precipitation described for the Atacama. Multiple interrelations between solar irradiance, climate, nutrient and vegetational changes could be controlling the abundance of waxes in time, and other proxies should be used to confirm this relationship. However, more comprehensive leaf wax analysis of the dominant vegetation and other midden series are required to understand better and quantify the link between climatic variability and n-alkyl leaf waxes under extreme arid environmental conditions. These records create an opportunity to complement other paleoclimate proxies with isotopic analysis and genetic information to a wide spatial range to understand the complex relationships between climate and desert vegetation where other paleoclimate records are scarce.</p>
</section>
<section id="data-availability" class="level1">
<h1>Data Availability</h1>
<p>All raw data and code used in this paper are publicly available for reuse via Zenodo and Github through this link:</p>
</section>
<section id="acknowledgments" class="level1">
<h1>Acknowledgments</h1>
<p>We thank Chris Moy, Jean Pierre Francois, indigenous community of Socaire and CONAF for help with sample analysis, logistical support in the field.</p>
</section>
<section id="financial-support" class="level1">
<h1>Financial support</h1>
<p>This research has been supported by the IEB (through ANID FB210006), FONDECYT (grants 1190398, 1191568, 11220930, 3180368), ANID-Millennium Science Initiative Program -NCN19_153 UPWELL</p>
</section>
<section id="competing-interests" class="level1">
<h1>Competing interests</h1>
<p>The authors declare that they have no conflict of interest</p>
</section>
<section id="bibliography-styles" class="level1">
<h1>Bibliography styles</h1>
<p>Here are two sample references: <span class="citation" data-cites="anjosMeasuringResilienceAssessing2018">Anjos and Toledo (<a href="#ref-anjosMeasuringResilienceAssessing2018" role="doc-biblioref">2018</a>)</span> <span class="citation" data-cites="arroyoEffectsAridityPlant1988">Arroyo et al. (<a href="#ref-arroyoEffectsAridityPlant1988" role="doc-biblioref">1988</a>)</span>.</p>
<p>By default, natbib will be used with the <code>authoryear</code> style, set in <code>classoption</code> variable in YAML. You can sets extra options with <code>natbiboptions</code> variable in YAML header. Example</p>
<pre><code>natbiboptions: longnamesfirst,angle,semicolon</code></pre>
<p>There are various more specific bibliography styles available at <a href="https://support.stmdocs.in/wiki/index.php?title=Model-wise_bibliographic_style_files" class="uri">https://support.stmdocs.in/wiki/index.php?title=Model-wise_bibliographic_style_files</a>. To use one of these, add it in the header using, for example, <code>biblio-style: model1-num-names</code>.</p>
</section>
<section id="equations" class="level1">
<h1>Equations</h1>
<p>Here is an equation: <span class="math display">\[
  f_{X}(x) = \left(\frac{\alpha}{\beta}\right)
  \left(\frac{x}{\beta}\right)^{\alpha-1}
  e^{-\left(\frac{x}{\beta}\right)^{\alpha}};
  \alpha,\beta,x &gt; 0 .
\]</span></p>
<p>Inline equations work as well: <span class="math inline">\(\sum_{i = 2}^\infty\{\alpha_i^\beta\}\)</span></p>
</section>
<section id="figures-and-tables" class="level1">
<h1>Figures and tables</h1>
<p><a href="#fig-meaningless">Figure&nbsp;2</a> is generated using an R chunk.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-meaningless" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Matías-Frugone-Álvarez_files/figure-html/fig-meaningless-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: A meaningless scatterplot</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tables-coming-from-r" class="level1">
<h1>Tables coming from R</h1>
<p>Tables can also be generated using R chunks, as shown in <a href="#tbl-simple">Table&nbsp;1</a> example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(mtcars)[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-simple" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1: Caption centered above table</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">mpg</th>
<th style="text-align: right;">cyl</th>
<th style="text-align: right;">disp</th>
<th style="text-align: right;">hp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mazda RX4</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">110</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mazda RX4 Wag</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Datsun 710</td>
<td style="text-align: right;">22.8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hornet 4 Drive</td>
<td style="text-align: right;">21.4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">258</td>
<td style="text-align: right;">110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hornet Sportabout</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">175</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valiant</td>
<td style="text-align: right;">18.1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">105</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-anjosMeasuringResilienceAssessing2018" class="csl-entry" role="doc-biblioentry">
Anjos, Luciano J. S., and Peter Mann de Toledo. 2018. <span>“Measuring Resilience and Assessing Vulnerability of Terrestrial Ecosystems to Climate Change in <span>South America</span>.”</span> <em>PLOS ONE</em> 13 (3): e0194654. <a href="https://doi.org/10.1371/journal.pone.0194654">https://doi.org/10.1371/journal.pone.0194654</a>.
</div>
<div id="ref-arroyoPlantPhenologicalPatterns1981" class="csl-entry" role="doc-biblioentry">
Arroyo, Mary T. Kalin, Juan J. Armesto, and Carolina Villagran. 1981. <span>“Plant <span>Phenological Patterns</span> in the <span>High Andean Cordillera</span> of <span>Central Chile</span>.”</span> <em>Journal of Ecology</em> 69 (1): 205–23. <a href="https://doi.org/10.2307/2259826">https://doi.org/10.2307/2259826</a>.
</div>
<div id="ref-arroyoEffectsAridityPlant1988" class="csl-entry" role="doc-biblioentry">
Arroyo, Mary T. Kalin, Francisco A. Squeo, Juan J. Armesto, and Carolina Villagran. 1988. <span>“Effects of <span>Aridity</span> on <span>Plant Diversity</span> in the <span>Northern Chilean Andes</span>: <span>Results</span> of a <span>Natural Experiment</span>.”</span> <em>Annals of the Missouri Botanical Garden</em> 75 (1): 55–78. <a href="https://doi.org/10.2307/2399466">https://doi.org/10.2307/2399466</a>.
</div>
<div id="ref-berdugoGlobalEcosystemThresholds2020" class="csl-entry" role="doc-biblioentry">
Berdugo, Miguel, Manuel Delgado-Baquerizo, Santiago Soliveres, Rocío Hernández-Clemente, Yanchuang Zhao, Juan J. Gaitán, Nicolas Gross, et al. 2020. <span>“Global Ecosystem Thresholds Driven by Aridity.”</span> <em>Science</em> 367 (6479): 787–90. <a href="https://doi.org/10.1126/science.aay5958">https://doi.org/10.1126/science.aay5958</a>.
</div>
<div id="ref-betancourt22000YearRecord2000" class="csl-entry" role="doc-biblioentry">
Betancourt, J. L., C. Latorre, J. A. Rech, J. Quade, and K. A. Rylander. 2000. <span>“A 22,000-<span>Year Record</span> of <span>Monsoonal Precipitation</span> from <span>Northern Chile</span>’s <span>Atacama Desert</span>.”</span> <em>Science</em> 289 (5484): 1542–46. <a href="https://doi.org/10.1126/science.289.5484.1542">https://doi.org/10.1126/science.289.5484.1542</a>.
</div>
<div id="ref-betancourtPaleomadriguerasRoedoresNuevo2002" class="csl-entry" role="doc-biblioentry">
Betancourt, Julio L., and Bárbara Saavedra. 2002. <span>“Paleomadrigueras de Roedores, Un Nuevo Método Para El Estudio Del <span>Cuaternario</span> En Zonas Áridas de <span>Sudamérica</span>.”</span> <em>Revista Chilena de Historia Natural</em> 75 (3): 527–46. <a href="https://doi.org/10.4067/S0716-078X2002000300005">https://doi.org/10.4067/S0716-078X2002000300005</a>.
</div>
<div id="ref-bushLeafWaxNalkane2013" class="csl-entry" role="doc-biblioentry">
Bush, Rosemary T., and Francesca A. McInerney. 2013. <span>“Leaf Wax n-Alkane Distributions in and Across Modern Plants: <span>Implications</span> for Paleoecology and Chemotaxonomy.”</span> <em>Geochimica Et Cosmochimica Acta</em> 117 (September): 161–79. <a href="https://doi.org/10.1016/j.gca.2013.04.016">https://doi.org/10.1016/j.gca.2013.04.016</a>.
</div>
<div id="ref-castanedaReviewMolecularOrganic2011" class="csl-entry" role="doc-biblioentry">
Castañeda, Isla S., and Stefan Schouten. 2011. <span>“A Review of Molecular Organic Proxies for Examining Modern and Ancient Lacustrine Environments.”</span> <em>Quaternary Science Reviews</em> 30 (21): 2851–91. <a href="https://doi.org/10.1016/j.quascirev.2011.07.009">https://doi.org/10.1016/j.quascirev.2011.07.009</a>.
</div>
<div id="ref-chikaraishiCompoundspecificDDD13C2003" class="csl-entry" role="doc-biblioentry">
Chikaraishi, Yoshito, and Hiroshi Naraoka. 2003. <span>“Compound-Specific <span><span class="math inline">\(\delta\)</span>D</span> Analyses of n-Alkanes Extracted from Terrestrial and Aquatic Plants.”</span> <em>Phytochemistry</em> 63 (3): 361–71. <a href="https://doi.org/10.1016/S0031-9422(02)00749-5">https://doi.org/10.1016/S0031-9422(02)00749-5</a>.
</div>
<div id="ref-contrerasLeafWaxComposition2022" class="csl-entry" role="doc-biblioentry">
Contreras, Sergio, Manlio Landahur, Karla García, Claudio Latorre, Mark Reyers, Janet Rethemeyer, and Andrea Jaeschke. 2022. <span>“Leaf Wax Composition and Distribution of <span>Tillandsia</span> Landbeckii Reflects Moisture Gradient Across the Hyperarid <span>Atacama Desert</span>.”</span> <em>Plant Systematics and Evolution</em> 308 (1): 8. <a href="https://doi.org/10.1007/s00606-021-01800-0">https://doi.org/10.1007/s00606-021-01800-0</a>.
</div>
<div id="ref-diazNitrogenCyclingExtreme2016" class="csl-entry" role="doc-biblioentry">
Díaz, Francisca P., Matías Frugone, Rodrigo A. Gutiérrez, and Claudio Latorre. 2016. <span>“Nitrogen Cycling in an Extreme Hyperarid Environment Inferred from D15 <span>N</span> Analyses of Plants, Soils and Herbivore Diet.”</span> <em>Scientific Reports</em> 6 (1): 22226. <a href="https://doi.org/10.1038/srep22226">https://doi.org/10.1038/srep22226</a>.
</div>
<div id="ref-diazMultiscaleClimateChange2019" class="csl-entry" role="doc-biblioentry">
Díaz, Francisca P., Claudio Latorre, Gabriela Carrasco-Puga, Jamie R. Wood, Janet M. Wilmshurst, Daniela C. Soto, Theresa L. Cole, and Rodrigo A. Gutiérrez. 2019. <span>“Multiscale Climate Change Impacts on Plant Diversity in the <span>Atacama Desert</span>.”</span> <em>Global Change Biology</em> 25 (5): 1733–45. <a href="https://doi.org/10.1111/gcb.14583">https://doi.org/10.1111/gcb.14583</a>.
</div>
<div id="ref-diazRodentMiddensReveal2012" class="csl-entry" role="doc-biblioentry">
Díaz, Francisca P., Claudio Latorre, Antonio Maldonado, Jay Quade, and Julio L. Betancourt. 2012. <span>“Rodent Middens Reveal Episodic, Long-Distance Plant Colonizations Across the Hyperarid <span>Atacama Desert</span> over the Last 34,000 Years.”</span> <em>Journal of Biogeography</em> 39 (3): 510–25. <a href="https://doi.org/10.1111/j.1365-2699.2011.02617.x">https://doi.org/10.1111/j.1365-2699.2011.02617.x</a>.
</div>
<div id="ref-didykOrganicGeochemicalIndicators1978" class="csl-entry" role="doc-biblioentry">
Didyk, B. M., B. R. T. Simoneit, S. C. Brassell, and G. Eglinton. 1978. <span>“Organic Geochemical Indicators of Palaeoenvironmental Conditions of Sedimentation.”</span> <em>Nature</em> 272 (5650): 216–22. <a href="https://doi.org/10.1038/272216a0">https://doi.org/10.1038/272216a0</a>.
</div>
<div id="ref-dussarratPredictiveMetabolomicsMultiple2022" class="csl-entry" role="doc-biblioentry">
Dussarrat, Thomas, Sylvain Prigent, Claudio Latorre, Stéphane Bernillon, Amélie Flandin, Francisca P. Díaz, Cédric Cassan, et al. 2022. <span>“Predictive Metabolomics of Multiple <span>Atacama</span> Plant Species Unveils a Core Set of Generic Metabolites for Extreme Climate Resilience.”</span> <em>New Phytologist</em>, March. <a href="https://doi.org/10.1111/nph.18095">https://doi.org/10.1111/nph.18095</a>.
</div>
<div id="ref-eglintonChemicalFossilsCombined1973" class="csl-entry" role="doc-biblioentry">
Eglinton, G. 1973. <span>“Chemical Fossils: A Combined Organic Geochemical and Environmental Approach.”</span> <em>Pure and Applied Chemistry</em> 34: 611–32.
</div>
<div id="ref-eshelPlantEcologicalGenomics2021" class="csl-entry" role="doc-biblioentry">
Eshel, Gil, Viviana Araus, Soledad Undurraga, Daniela C. Soto, Carol Moraga, Alejandro Montecinos, Tomás Moyano, et al. 2021. <span>“Plant Ecological Genomics at the Limits of Life in the <span>Atacama Desert</span>.”</span> <em>Proceedings of the National Academy of Sciences</em> 118 (46). <a href="https://doi.org/10.1073/pnas.2101177118">https://doi.org/10.1073/pnas.2101177118</a>.
</div>
<div id="ref-gayoLateQuaternaryHydrological2012" class="csl-entry" role="doc-biblioentry">
Gayo, Eugenia M., Claudio Latorre, Teresa E. Jordan, Peter L. Nester, Sergio A. Estay, Karla F. Ojeda, and Calogero M. Santoro. 2012. <span>“Late <span>Quaternary</span> Hydrological and Ecological Changes in the Hyperarid Core of the Northern <span>Atacama Desert</span> (~&nbsp;21).”</span> <em>Earth-Science Reviews</em> 113 (3): 120–40. <a href="https://doi.org/10.1016/j.earscirev.2012.04.003">https://doi.org/10.1016/j.earscirev.2012.04.003</a>.
</div>
<div id="ref-gonzalez-pinillaHighLowlatitudeForcings2021" class="csl-entry" role="doc-biblioentry">
González-Pinilla, Francisco J., Claudio Latorre, Maisa Rojas, John Houston, M. Ignacia Rocuant, Antonio Maldonado, Calogero M. Santoro, Jay Quade, and Julio L. Betancourt. 2021. <span>“High- and Low-Latitude Forcings Drive <span>Atacama Desert</span> Rainfall Variations over the Past 16,000 Years.”</span> <em>Science Advances</em> 7 (38): eabg1333. <a href="https://doi.org/10.1126/sciadv.abg1333">https://doi.org/10.1126/sciadv.abg1333</a>.
</div>
<div id="ref-grosjeanMidHoloceneClimateSouthCentral2001" class="csl-entry" role="doc-biblioentry">
Grosjean, Martin. 2001. <span>“Mid-<span>Holocene Climate</span> in the <span>South-Central Andes</span>: <span>Humid</span> or <span>Dry</span>?”</span> <em>Science</em> 292 (5526): 2391–91. <a href="https://doi.org/10.1126/science.292.5526.2391a">https://doi.org/10.1126/science.292.5526.2391a</a>.
</div>
<div id="ref-grosjeanLateglacialEarlyMiddle1994" class="csl-entry" role="doc-biblioentry">
Grosjean, Martin, and A. Lautaro Núñez. 1994. <span>“Lateglacial, Early and Middle Holocene Environments, Human Occupation, and Resource Use in the <span>Atacama</span> (<span>Northern Chile</span>).”</span> <em>Geoarchaeology</em> 9 (4): 271–86. <a href="https://doi.org/10.1002/gea.3340090402">https://doi.org/10.1002/gea.3340090402</a>.
</div>
<div id="ref-halbritterTraitDifferentiationAdaptation2018" class="csl-entry" role="doc-biblioentry">
Halbritter, Aud H., Simone Fior, Irene Keller, Regula Billeter, Peter J. Edwards, Rolf Holderegger, Sophie Karrenberg, Andrea R. Pluess, Alex Widmer, and Jake M. Alexander. 2018. <span>“Trait Differentiation and Adaptation of Plants Along Elevation Gradients.”</span> <em>Journal of Evolutionary Biology</em> 31 (6): 784–800. <a href="https://doi.org/10.1111/jeb.13262">https://doi.org/10.1111/jeb.13262</a>.
</div>
<div id="ref-hogg_2020" class="csl-entry" role="doc-biblioentry">
Hogg, Alan G, Timothy J Heaton, Quan Hua, Jonathan G Palmer, Chris SM Turney, John Southon, Alex Bayliss, et al. 2020. <span>“SHCal20 Southern Hemisphere Calibration, 0–55,000 Years Cal BP.”</span> <em>Radiocarbon</em> 62 (4): 759–78. <a href="https://doi.org/10.1017/RDC.2020.59">https://doi.org/10.1017/RDC.2020.59</a>.
</div>
<div id="ref-houstonCentralAndeanWestslope2003" class="csl-entry" role="doc-biblioentry">
Houston, John, and Adrian J. Hartley. 2003. <span>“The Central <span>Andean</span> West-Slope Rainshadow and Its Potential Contribution to the Origin of Hyper-Aridity in the <span>Atacama Desert</span>.”</span> <em>International Journal of Climatology</em> 23 (12): 1453–64. <a href="https://doi.org/10.1002/joc.938">https://doi.org/10.1002/joc.938</a>.
</div>
<div id="ref-inglisBiomarkerApproachesReconstructing2022" class="csl-entry" role="doc-biblioentry">
Inglis, Gordon, Tripti Bhattacharya, Jordon Hemingway, Emily Hollingsworth, Sarah Feakins, and Jessica E. Tierney. 2022. <span>“Biomarker Approaches for Reconstructing Terrestrial Environmental Change.”</span> <em>Annual Review of Earth and Planetary Sciences</em> 50 (February): 369–94. <a href="https://doi.org/10.1146/annurev-earth-032320-095943">https://doi.org/10.1146/annurev-earth-032320-095943</a>.
</div>
<div id="ref-jaraDidModernPrecipitation2022" class="csl-entry" role="doc-biblioentry">
Jara, Ignacio A., Antonio Maldonado, and María Eugenia de Porras. 2022. <span>“Did <span>Modern Precipitation Drivers Influence Centennial Trends</span> in the <span>Highlands</span> of the <span>Atacama Desert During</span> the <span>Most Recent Millennium</span>?”</span> <em>Geophysical Research Letters</em> 49 (1): e2021GL095927. <a href="https://doi.org/10.1029/2021GL095927">https://doi.org/10.1029/2021GL095927</a>.
</div>
<div id="ref-kolattukudyPlantWaxes1970" class="csl-entry" role="doc-biblioentry">
Kolattukudy, P. E. 1970. <span>“Plant Waxes.”</span> <em>Lipids</em> 5 (2): 259–75. <a href="https://doi.org/10.1007/BF02532477">https://doi.org/10.1007/BF02532477</a>.
</div>
<div id="ref-latorreLateQuaternaryVegetation2006" class="csl-entry" role="doc-biblioentry">
Latorre, Claudio, Julio L. Betancourt, and Mary T. K. Arroyo. 2006. <span>“Late <span>Quaternary</span> Vegetation and Climate History of a Perennial River Canyon in the <span>Río Salado</span> Basin (22) of <span>Northern Chile</span>.”</span> <em>Quaternary Research</em> 65 (3): 450–66. <a href="https://doi.org/10.1016/j.yqres.2006.02.002">https://doi.org/10.1016/j.yqres.2006.02.002</a>.
</div>
<div id="ref-latorreVegetationInvasionsAbsolute2002" class="csl-entry" role="doc-biblioentry">
Latorre, Claudio, Julio L. Betancourt, Kate A. Rylander, and Jay Quade. 2002. <span>“Vegetation Invasions into Absolute Desert: <span>A</span> 45.000 Yr Rodent Midden Record from the <span>Calama</span> de <span>Atacama</span> Basins, Northern <span>Chile</span> (Lat 22).”</span> <em>GSA Bulletin</em> 114 (3): 349–66. <a href="https://doi.org/10.1130/0016-7606(2002)114<0349:VIIADA>2.0.CO;2">https://doi.org/10.1130/0016-7606(2002)114&lt;0349:VIIADA&gt;2.0.CO;2</a>.
</div>
<div id="ref-lavorelPredictingChangesCommunity2002" class="csl-entry" role="doc-biblioentry">
Lavorel, S., and E. Garnier. 2002. <span>“Predicting Changes in Community Composition and Ecosystem Functioning from Plant Traits: Revisiting the <span>Holy Grail</span>.”</span> <em>Functional Ecology</em> 16 (5): 545–56. <a href="https://doi.org/10.1046/j.1365-2435.2002.00664.x">https://doi.org/10.1046/j.1365-2435.2002.00664.x</a>.
</div>
<div id="ref-luningMedievalClimateAnomaly2019" class="csl-entry" role="doc-biblioentry">
Lüning, Sebastian, Mariusz Gałka, Florencia Paula Bamonte, Felipe García Rodríguez, and Fritz Vahrenholt. 2019. <span>“The <span>Medieval Climate Anomaly</span> in <span>South America</span>.”</span> <em>Quaternary International</em> 508 (March): 70–87. <a href="https://doi.org/10.1016/j.quaint.2018.10.041">https://doi.org/10.1016/j.quaint.2018.10.041</a>.
</div>
<div id="ref-maldonadoPollenAnalyses502005" class="csl-entry" role="doc-biblioentry">
Maldonado, Antonio, Julio L. Betancourt, Claudio Latorre, and Carolina Villagran. 2005. <span>“Pollen Analyses from a 50 000-Yr Rodent Midden Series in the Southern <span>Atacama Desert</span> (25 30<span><span class="math inline">\({'}\)</span></span> <span>S</span>).”</span> <em>Journal of Quaternary Science</em> 20 (5): 493–507.
</div>
<div id="ref-martinLakeTaucaHighstand2018" class="csl-entry" role="doc-biblioentry">
Martin, Léo C. P., Pierre-Henri Blard, Jérôme Lavé, Thomas Condom, Mélody Prémaillon, Vincent Jomelli, Daniel Brunstein, et al. 2018. <span>“Lake <span>Tauca</span> Highstand (<span>Heinrich Stadial</span> 1a) Driven by a Southward Shift of the <span>Bolivian High</span>.”</span> <em>Science Advances</em> 4 (8): eaar2514. <a href="https://doi.org/10.1126/sciadv.aar2514">https://doi.org/10.1126/sciadv.aar2514</a>.
</div>
<div id="ref-morchenFingerprintPlantLife2021" class="csl-entry" role="doc-biblioentry">
Mörchen, R., W. Amelung, C. Giese, T. Böhnert, J. Ruhm, and E. Lehndorff. 2021. <span>“Fingerprint of Plant Life in the <span>Atacama Desert</span> <span>Insights</span> from n-Alkane Analyses.”</span> <em>Organic Geochemistry</em> 151 (January): 104145. <a href="https://doi.org/10.1016/j.orggeochem.2020.104145">https://doi.org/10.1016/j.orggeochem.2020.104145</a>.
</div>
<div id="ref-mucinaBiomeEvolutionCrucial2019" class="csl-entry" role="doc-biblioentry">
Mucina, Ladislav. 2019. <span>“Biome: Evolution of a Crucial Ecological and Biogeographical Concept.”</span> <em>New Phytologist</em> 222 (1): 97–114. <a href="https://doi.org/10.1111/nph.15609">https://doi.org/10.1111/nph.15609</a>.
</div>
<div id="ref-mujicaLateQuaternaryClimate2015" class="csl-entry" role="doc-biblioentry">
Mujica, María Isabel, Claudio Latorre, Antonio Maldonado, Leticia González-Silvestre, Raquel Pinto, Ricardo de Pol-Holz, and Calogero M. Santoro. 2015. <span>“Late <span>Quaternary</span> Climate Change, Relict Populations and Present-Day Refugia in the Northern <span>Atacama Desert</span>: A Case Study from <span>Quebrada La Higuera</span> (18&nbsp;<span>S</span>).”</span> <em>Journal of Biogeography</em> 42 (1): 76–88. <a href="https://doi.org/10.1111/jbi.12383">https://doi.org/10.1111/jbi.12383</a>.
</div>
<div id="ref-navarroPhenotypicPlasticitySelection2022" class="csl-entry" role="doc-biblioentry">
Navarro, Jocelyn, John M. Powers, Ayaka Paul, and Diane R. Campbell. 2022. <span>“Phenotypic Plasticity and Selection on Leaf Traits in Response to Snowmelt Timing and Summer Precipitation.”</span> <em>New Phytologist</em> 234 (4): 1477–90. <a href="https://doi.org/10.1111/nph.18084">https://doi.org/10.1111/nph.18084</a>.
</div>
<div id="ref-nesterPerennialStreamDischarge2007" class="csl-entry" role="doc-biblioentry">
Nester, Peter L., Eugenia Gayó, Claudio Latorre, Teresa E. Jordan, and Nicolás Blanco. 2007. <span>“Perennial Stream Discharge in the Hyperarid <span>Atacama Desert</span> of Northern <span>Chile</span> During the Latest <span>Pleistocene</span>.”</span> <em>Proceedings of the National Academy of Sciences</em> 104 (50): 19724–29. <a href="https://doi.org/10.1073/pnas.0705373104">https://doi.org/10.1073/pnas.0705373104</a>.
</div>
<div id="ref-pollardBuildingLipidBarriers2008" class="csl-entry" role="doc-biblioentry">
Pollard, Mike, Fred Beisson, Yonghua Li, and John B. Ohlrogge. 2008. <span>“Building Lipid Barriers: Biosynthesis of Cutin and Suberin.”</span> <em>Trends in Plant Science</em> 13 (5): 236–46. <a href="https://doi.org/10.1016/j.tplants.2008.03.003">https://doi.org/10.1016/j.tplants.2008.03.003</a>.
</div>
<div id="ref-quadeCentralAndean282022" class="csl-entry" role="doc-biblioentry">
Quade, Jay, Elad Dente, Alyson Cartwright, Adam Hudson, Sebastian Jimenez-Rodriguez, and David McGee. 2022. <span>“Central <span>Andean</span> (28) Flood Record 0 Ka from <span>Salinas</span> Del <span>Bebedero</span>, <span>Argentina</span>.”</span> <em>Quaternary Research</em>, April, 1–27. <a href="https://doi.org/10.1017/qua.2022.1">https://doi.org/10.1017/qua.2022.1</a>.
</div>
<div id="ref-quadePaleowetlandsRegionalClimate2008" class="csl-entry" role="doc-biblioentry">
Quade, Jay, Jason A. Rech, Julio L. Betancourt, Claudio Latorre, Barbra Quade, Kate Aasen Rylander, and Timothy Fisher. 2008. <span>“Paleowetlands and Regional Climate Change in the Central <span>Atacama Desert</span>, Northern Chile.”</span> <em>Quaternary Research</em> 69 (3): 343–60. <a href="https://doi.org/10.1016/j.yqres.2008.01.003">https://doi.org/10.1016/j.yqres.2008.01.003</a>.
</div>
<div id="ref-rabatelChronologyLittleIce2008b" class="csl-entry" role="doc-biblioentry">
Rabatel, Antoine, Bernard Francou, Vincent Jomelli, Philippe Naveau, and Delphine Grancher. 2008. <span>“A Chronology of the <span>Little Ice Age</span> in the Tropical <span>Andes</span> of <span>Bolivia</span> (16) and Its Implications for Climate Reconstruction.”</span> <em>Quaternary Research</em> 70 (2): 198–212. <a href="https://doi.org/10.1016/j.yqres.2008.02.012">https://doi.org/10.1016/j.yqres.2008.02.012</a>.
</div>
<div id="ref-rabatelDatingLittleIce2005" class="csl-entry" role="doc-biblioentry">
Rabatel, Antoine, Vincent Jomelli, Philippe Naveau, Bernard Francou, and Delphine Grancher. 2005. <span>“Dating of <span>Little Ice Age</span> Glacier Fluctuations in the Tropical <span>Andes</span>: <span>Charquini</span> Glaciers, <span>Bolivia</span>, 16.”</span> <em>Comptes Rendus Geoscience</em> 337 (15): 1311–22. <a href="https://doi.org/10.1016/j.crte.2005.07.009">https://doi.org/10.1016/j.crte.2005.07.009</a>.
</div>
<div id="ref-rechLateQuaternaryPaleohydrology2002" class="csl-entry" role="doc-biblioentry">
Rech, Jason A., Jay Quade, and Julio L. Betancourt. 2002. <span>“Late <span>Quaternary</span> Paleohydrology of the Central <span>Atacama Desert</span> (Lat 22), <span>Chile</span>.”</span> <em>GSA Bulletin</em> 114 (3): 334–48. <a href="https://doi.org/10.1130/0016-7606(2002)114<0334:LQPOTC>2.0.CO;2">https://doi.org/10.1130/0016-7606(2002)114&lt;0334:LQPOTC&gt;2.0.CO;2</a>.
</div>
<div id="ref-rodbell700000Years2022" class="csl-entry" role="doc-biblioentry">
Rodbell, D. T., R. G. Hatfield, M. B. Abbott, C. Y. Chen, A. Woods, J. S. Stoner, D. McGee, et al. 2022. <span>“700,000 Years of Tropical <span>Andean</span> Glaciation.”</span> <em>Nature</em> 607 (7918): 301–6. <a href="https://doi.org/10.1038/s41586-022-04873-0">https://doi.org/10.1038/s41586-022-04873-0</a>.
</div>
<div id="ref-sachseDDValuesIndividual2006" class="csl-entry" role="doc-biblioentry">
Sachse, Dirk, Jens Radke, and Gerd Gleixner. 2006. <span>“<span><span class="math inline">\(\delta\)</span>D</span> Values of Individual n-Alkanes from Terrestrial Plants Along a Climatic Gradient <span>Implications</span> for the Sedimentary Biomarker Record.”</span> <em>Organic Geochemistry</em> 37 (4): 469–83. <a href="https://doi.org/10.1016/j.orggeochem.2005.12.003">https://doi.org/10.1016/j.orggeochem.2005.12.003</a>.
</div>
<div id="ref-schefussCarbonIsotopeAnalyses2003" class="csl-entry" role="doc-biblioentry">
Schefuß, Enno, Volker Ratmeyer, Jan-Berend W. Stuut, J. H. Fred Jansen, and Jaap S. Sinninghe Damsté. 2003. <span>“Carbon Isotope Analyses of n-Alkanes in Dust from the Lower Atmosphere over the Central Eastern <span>Atlantic</span>.”</span> <em>Geochimica Et Cosmochimica Acta</em> 67 (10): 1757–67. <a href="https://doi.org/10.1016/S0016-7037(02)01414-X">https://doi.org/10.1016/S0016-7037(02)01414-X</a>.
</div>
<div id="ref-smithInfluencePhysiologyClimate2006" class="csl-entry" role="doc-biblioentry">
Smith, Francesca A., and Katherine H. Freeman. 2006. <span>“Influence of Physiology and Climate on <span><span class="math inline">\(\delta\)</span>D</span> of Leaf Wax n-Alkanes from <span>C3</span> and <span>C4</span> Grasses.”</span> <em>Geochimica Et Cosmochimica Acta</em> 70 (5): 1172–87. <a href="https://doi.org/10.1016/j.gca.2005.11.006">https://doi.org/10.1016/j.gca.2005.11.006</a>.
</div>
<div id="ref-spaulding1990vegetational" class="csl-entry" role="doc-biblioentry">
Spaulding, W Geoffrey. 1990. <span>“Vegetational and Climatic Development of the Mojave Desert: The Last Glacial Maximum.”</span> <em>Packrat Middens: The Last 40,000 Years of Biotic Change</em>, 166.
</div>
<div id="ref-stotzGlobalTrendsPhenotypic2021" class="csl-entry" role="doc-biblioentry">
Stotz, Gisela C., Cristian Salgado-Luarte, Víctor M. Escobedo, Fernando Valladares, and Ernesto Gianoli. 2021. <span>“Global Trends in Phenotypic Plasticity of Plants.”</span> <em>Ecology Letters</em> 24 (10): 2267–81. <a href="https://doi.org/10.1111/ele.13827">https://doi.org/10.1111/ele.13827</a>.
</div>
<div id="ref-strikisSouthAmericanMonsoon2018" class="csl-entry" role="doc-biblioentry">
Stríkis, Nicolás M., Francisco W. Cruz, Eline A. S. Barreto, Filipa Naughton, Mathias Vuille, Hai Cheng, Antje H. L. Voelker, et al. 2018. <span>“South <span>American</span> Monsoon Response to Iceberg Discharge in the <span>North Atlantic</span>.”</span> <em>Proceedings of the National Academy of Sciences</em> 115 (15): 3788–93. <a href="https://doi.org/10.1073/pnas.1717784115">https://doi.org/10.1073/pnas.1717784115</a>.
</div>
<div id="ref-valero-garcesLimnogeologyLagunaMiscanti1996" class="csl-entry" role="doc-biblioentry">
Valero-Garcés, Blas L., Martin Grosjean, Antje Schwalb, Mebus Geyh, Bruno Messerli, and Kerry Kelts. 1996. <span>“Limnogeology of <span>Laguna Miscanti</span>: Evidence for Mid to Late <span>Holocene</span> Moisture Changes in the <span>Atacama Altiplano</span> (<span>Northern Chile</span>).”</span> <em>Journal of Paleolimnology</em> 16 (1): 1–21. <a href="https://doi.org/10.1007/BF00173268">https://doi.org/10.1007/BF00173268</a>.
</div>
<div id="ref-villagranVegetationHighAndean1981" class="csl-entry" role="doc-biblioentry">
Villagrán, C., J. J. Armesto, and M. T. Kalin Arroyo. 1981. <span>“Vegetation in a High <span>Andean</span> Transect Between <span>Turi</span> and <span>Cerro León</span> in <span>Northern Chile</span>.”</span> <em>Vegetatio</em> 48 (1): 3–16. <a href="https://doi.org/10.1007/BF00117356">https://doi.org/10.1007/BF00117356</a>.
</div>
<div id="ref-villagranEfectosDesertizacionDistribucion1983" class="csl-entry" role="doc-biblioentry">
Villagrán, Carolina, Mary T. Kalin Arroyo, and Clodomiro Marticorena. 1983. <span>“Efectos de La Desertización En La Distribución de La Flora Andina de <span>Chile</span>.”</span>
</div>
<div id="ref-vonguntenQuantitativeHighresolutionSummer2009" class="csl-entry" role="doc-biblioentry">
von Gunten, Lucien, Martin Grosjean, Bert Rein, Roberto Urrutia, and Peter Appleby. 2009. <span>“A Quantitative High-Resolution Summer Temperature Reconstruction Based on Sedimentary Pigments from <span>Laguna Aculeo</span>, Central <span>Chile</span>, Back to <span>AD</span> 850.”</span> <em>The Holocene</em> 19 (6): 873–81. <a href="https://doi.org/10.1177/0959683609336573">https://doi.org/10.1177/0959683609336573</a>.
</div>
<div id="ref-workmanLandscapeEvolutionEnvironmental2020" class="csl-entry" role="doc-biblioentry">
Workman, T. Race, Jason A. Rech, Eugenia M. Gayó, Calogero M. Santoro, Paula C. Ugalde, Ricardo De Pol-Holz, Jose M. Capriles, and Claudio Latorre. 2020. <span>“Landscape Evolution and the Environmental Context of Human Occupation of the Southern Pampa Del Tamarugal, <span>Atacama Desert</span>, <span>Chile</span>.”</span> <em>Quaternary Science Reviews</em> 243 (September): 106502. <a href="https://doi.org/10.1016/j.quascirev.2020.106502">https://doi.org/10.1016/j.quascirev.2020.106502</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>